// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "github.com/zzzhr1990/common-grpc/go/common"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GrpcUser struct {
	Uuid                 int64    `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CountryCode          string   `protobuf:"bytes,3,opt,name=countryCode,proto3" json:"countryCode,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	CreateTime           string   `protobuf:"bytes,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	CreateIp             string   `protobuf:"bytes,6,opt,name=createIp,proto3" json:"createIp,omitempty"`
	Ssid                 string   `protobuf:"bytes,7,opt,name=ssid,proto3" json:"ssid,omitempty"`
	Icon                 string   `protobuf:"bytes,8,opt,name=icon,proto3" json:"icon,omitempty"`
	SpaceUsed            uint64   `protobuf:"varint,9,opt,name=spaceUsed,proto3" json:"spaceUsed,omitempty"`
	SpaceCapacity        uint64   `protobuf:"varint,10,opt,name=spaceCapacity,proto3" json:"spaceCapacity,omitempty"`
	Type                 int32    `protobuf:"varint,11,opt,name=type,proto3" json:"type,omitempty"`
	Status               int32    `protobuf:"varint,12,opt,name=status,proto3" json:"status,omitempty"`
	Version              int32    `protobuf:"varint,13,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrpcUser) Reset()         { *m = GrpcUser{} }
func (m *GrpcUser) String() string { return proto.CompactTextString(m) }
func (*GrpcUser) ProtoMessage()    {}
func (*GrpcUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{0}
}

func (m *GrpcUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcUser.Unmarshal(m, b)
}
func (m *GrpcUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcUser.Marshal(b, m, deterministic)
}
func (m *GrpcUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcUser.Merge(m, src)
}
func (m *GrpcUser) XXX_Size() int {
	return xxx_messageInfo_GrpcUser.Size(m)
}
func (m *GrpcUser) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcUser.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcUser proto.InternalMessageInfo

func (m *GrpcUser) GetUuid() int64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

func (m *GrpcUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GrpcUser) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *GrpcUser) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *GrpcUser) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *GrpcUser) GetCreateIp() string {
	if m != nil {
		return m.CreateIp
	}
	return ""
}

func (m *GrpcUser) GetSsid() string {
	if m != nil {
		return m.Ssid
	}
	return ""
}

func (m *GrpcUser) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *GrpcUser) GetSpaceUsed() uint64 {
	if m != nil {
		return m.SpaceUsed
	}
	return 0
}

func (m *GrpcUser) GetSpaceCapacity() uint64 {
	if m != nil {
		return m.SpaceCapacity
	}
	return 0
}

func (m *GrpcUser) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *GrpcUser) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GrpcUser) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func init() {
	proto.RegisterType((*GrpcUser)(nil), "services.GrpcUser")
}

func init() { proto.RegisterFile("user/user.proto", fileDescriptor_ed89022014131a74) }

var fileDescriptor_ed89022014131a74 = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x4f, 0x8b, 0xdb, 0x30,
	0x10, 0xc5, 0xe3, 0xfc, 0x75, 0x94, 0x86, 0x80, 0x48, 0x8b, 0x30, 0xa5, 0x98, 0xd0, 0x83, 0x2f,
	0xb5, 0x9b, 0xa6, 0x84, 0xe6, 0x9a, 0x50, 0x4a, 0xae, 0x6e, 0x73, 0xe9, 0x65, 0x71, 0xe4, 0xc1,
	0x11, 0xac, 0x25, 0x21, 0xc9, 0x01, 0xe7, 0xba, 0x5f, 0x72, 0x3f, 0xce, 0x62, 0x29, 0xde, 0x64,
	0x61, 0x2f, 0xf6, 0xbc, 0xdf, 0x7b, 0x12, 0x62, 0x66, 0xd0, 0xac, 0xd2, 0xa0, 0x92, 0xe6, 0x13,
	0x4b, 0x25, 0x8c, 0xc0, 0xbe, 0x06, 0x75, 0x66, 0x14, 0x74, 0x10, 0x50, 0x51, 0x96, 0x82, 0x27,
	0xee, 0xf7, 0x00, 0xdc, 0x30, 0x53, 0xbb, 0xd4, 0xe2, 0xb9, 0x8b, 0xfc, 0x3f, 0x4a, 0xd2, 0x83,
	0x06, 0x85, 0x31, 0xea, 0x57, 0x15, 0xcb, 0x89, 0x17, 0x7a, 0x51, 0x2f, 0xb5, 0x75, 0xc3, 0x78,
	0x56, 0x02, 0xe9, 0x86, 0x5e, 0x34, 0x4e, 0x6d, 0x8d, 0x43, 0x34, 0xa1, 0xa2, 0xe2, 0x46, 0xd5,
	0x3b, 0x91, 0x03, 0xe9, 0x59, 0xeb, 0x1e, 0xe1, 0x39, 0x1a, 0xc8, 0x93, 0xe0, 0x40, 0xfa, 0xd6,
	0x73, 0x02, 0x7f, 0x41, 0x88, 0x2a, 0xc8, 0x0c, 0xfc, 0x63, 0x25, 0x90, 0x81, 0xb5, 0xee, 0x08,
	0x0e, 0x90, 0xef, 0xd4, 0x5e, 0x92, 0xa1, 0x75, 0x5f, 0x75, 0xf3, 0x0e, 0xad, 0x59, 0x4e, 0x46,
	0xee, 0x1d, 0x4d, 0xdd, 0x30, 0x46, 0x05, 0x27, 0xbe, 0x63, 0x4d, 0x8d, 0x3f, 0xa3, 0xb1, 0x96,
	0x19, 0x85, 0x83, 0x86, 0x9c, 0x8c, 0x43, 0x2f, 0xea, 0xa7, 0x37, 0x80, 0xbf, 0xa2, 0xa9, 0x15,
	0xbb, 0x4c, 0x66, 0x94, 0x99, 0x9a, 0x20, 0x9b, 0x78, 0x0b, 0x9b, 0x7b, 0x4d, 0x2d, 0x81, 0x4c,
	0x42, 0x2f, 0x1a, 0xa4, 0xb6, 0xc6, 0x9f, 0xd0, 0x50, 0x9b, 0xcc, 0x54, 0x9a, 0x7c, 0xb0, 0xf4,
	0xaa, 0x30, 0x41, 0xa3, 0x33, 0x28, 0xcd, 0x04, 0x27, 0x53, 0x6b, 0xb4, 0xf2, 0xc7, 0x93, 0x87,
	0x66, 0x6d, 0x6b, 0xff, 0xba, 0x59, 0xe0, 0x5f, 0x6d, 0x07, 0x5c, 0xbf, 0xe3, 0x76, 0x46, 0x71,
	0x1b, 0x0c, 0xe6, 0x37, 0xb6, 0x15, 0xe2, 0xf1, 0xb7, 0x1d, 0xd6, 0xa2, 0x83, 0xd7, 0x68, 0x54,
	0x80, 0xb1, 0xc7, 0x3e, 0xde, 0x22, 0x7b, 0x6e, 0xd6, 0x3f, 0x5d, 0x26, 0x78, 0xe7, 0xb6, 0x45,
	0x67, 0xbb, 0xfa, 0xbf, 0x2c, 0x98, 0x39, 0x55, 0xc7, 0x98, 0x8a, 0x32, 0xb9, 0x5c, 0x2e, 0x27,
	0xb5, 0xdc, 0x6c, 0xbe, 0x5f, 0x97, 0xe1, 0x5b, 0xa1, 0x24, 0x4d, 0x0a, 0x91, 0xb4, 0x47, 0xed,
	0x06, 0x1d, 0x87, 0x76, 0x39, 0x56, 0x2f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x78, 0xbc, 0x34,
	0x55, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GrpcUserServiceClient is the client API for GrpcUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpcUserServiceClient interface {
	CreateUser(ctx context.Context, in *GrpcUser, opts ...grpc.CallOption) (*common.BoolEntity, error)
	GetUser(ctx context.Context, in *common.Int64Entity, opts ...grpc.CallOption) (*GrpcUser, error)
}

type grpcUserServiceClient struct {
	cc *grpc.ClientConn
}

func NewGrpcUserServiceClient(cc *grpc.ClientConn) GrpcUserServiceClient {
	return &grpcUserServiceClient{cc}
}

func (c *grpcUserServiceClient) CreateUser(ctx context.Context, in *GrpcUser, opts ...grpc.CallOption) (*common.BoolEntity, error) {
	out := new(common.BoolEntity)
	err := c.cc.Invoke(ctx, "/services.GrpcUserService/createUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcUserServiceClient) GetUser(ctx context.Context, in *common.Int64Entity, opts ...grpc.CallOption) (*GrpcUser, error) {
	out := new(GrpcUser)
	err := c.cc.Invoke(ctx, "/services.GrpcUserService/getUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcUserServiceServer is the server API for GrpcUserService service.
type GrpcUserServiceServer interface {
	CreateUser(context.Context, *GrpcUser) (*common.BoolEntity, error)
	GetUser(context.Context, *common.Int64Entity) (*GrpcUser, error)
}

func RegisterGrpcUserServiceServer(s *grpc.Server, srv GrpcUserServiceServer) {
	s.RegisterService(&_GrpcUserService_serviceDesc, srv)
}

func _GrpcUserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcUserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.GrpcUserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcUserServiceServer).CreateUser(ctx, req.(*GrpcUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcUserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Int64Entity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcUserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.GrpcUserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcUserServiceServer).GetUser(ctx, req.(*common.Int64Entity))
	}
	return interceptor(ctx, in, info, handler)
}

var _GrpcUserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.GrpcUserService",
	HandlerType: (*GrpcUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createUser",
			Handler:    _GrpcUserService_CreateUser_Handler,
		},
		{
			MethodName: "getUser",
			Handler:    _GrpcUserService_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/user.proto",
}
