// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/balance.proto

package balance

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Balance struct {
	Identity             int64    `protobuf:"varint,1,opt,name=identity,proto3" json:"identity,omitempty"`
	SpaceUsed            int64    `protobuf:"varint,2,opt,name=spaceUsed,proto3" json:"spaceUsed,omitempty"`
	SpaceLimit           int64    `protobuf:"varint,3,opt,name=spaceLimit,proto3" json:"spaceLimit,omitempty"`
	TrafficUsed          int64    `protobuf:"varint,4,opt,name=trafficUsed,proto3" json:"trafficUsed,omitempty"`
	TrafficLimit         int64    `protobuf:"varint,5,opt,name=trafficLimit,proto3" json:"trafficLimit,omitempty"`
	OfflineTaskUsed      int64    `protobuf:"varint,6,opt,name=OfflineTaskUsed,proto3" json:"OfflineTaskUsed,omitempty"`
	OfflineTaskLimit     int64    `protobuf:"varint,7,opt,name=OfflineTaskLimit,proto3" json:"OfflineTaskLimit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Balance) Reset()         { *m = Balance{} }
func (m *Balance) String() string { return proto.CompactTextString(m) }
func (*Balance) ProtoMessage()    {}
func (*Balance) Descriptor() ([]byte, []int) {
	return fileDescriptor_419eb21cb419e954, []int{0}
}

func (m *Balance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Balance.Unmarshal(m, b)
}
func (m *Balance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Balance.Marshal(b, m, deterministic)
}
func (m *Balance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Balance.Merge(m, src)
}
func (m *Balance) XXX_Size() int {
	return xxx_messageInfo_Balance.Size(m)
}
func (m *Balance) XXX_DiscardUnknown() {
	xxx_messageInfo_Balance.DiscardUnknown(m)
}

var xxx_messageInfo_Balance proto.InternalMessageInfo

func (m *Balance) GetIdentity() int64 {
	if m != nil {
		return m.Identity
	}
	return 0
}

func (m *Balance) GetSpaceUsed() int64 {
	if m != nil {
		return m.SpaceUsed
	}
	return 0
}

func (m *Balance) GetSpaceLimit() int64 {
	if m != nil {
		return m.SpaceLimit
	}
	return 0
}

func (m *Balance) GetTrafficUsed() int64 {
	if m != nil {
		return m.TrafficUsed
	}
	return 0
}

func (m *Balance) GetTrafficLimit() int64 {
	if m != nil {
		return m.TrafficLimit
	}
	return 0
}

func (m *Balance) GetOfflineTaskUsed() int64 {
	if m != nil {
		return m.OfflineTaskUsed
	}
	return 0
}

func (m *Balance) GetOfflineTaskLimit() int64 {
	if m != nil {
		return m.OfflineTaskLimit
	}
	return 0
}

func init() {
	proto.RegisterType((*Balance)(nil), "services.Balance")
}

func init() { proto.RegisterFile("user/balance.proto", fileDescriptor_419eb21cb419e954) }

var fileDescriptor_419eb21cb419e954 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcd, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xdf, 0xbc, 0xd1, 0xb6, 0x8e, 0xc5, 0x8f, 0x39, 0x85, 0x22, 0x52, 0x72, 0x2a, 0x42,
	0xb3, 0x7e, 0x80, 0x10, 0xbc, 0xf5, 0x2c, 0x08, 0x56, 0x2f, 0xde, 0x92, 0xed, 0x24, 0x5d, 0x6c,
	0xb2, 0x61, 0x77, 0xab, 0x98, 0x7f, 0x5e, 0x61, 0x92, 0xd6, 0x68, 0x2f, 0x1e, 0xe7, 0xf7, 0x7c,
	0x1c, 0x9e, 0x01, 0x5c, 0x5b, 0x32, 0x22, 0x4d, 0x56, 0x49, 0x29, 0x29, 0xaa, 0x8c, 0x76, 0x1a,
	0x07, 0x96, 0xcc, 0x9b, 0x92, 0x64, 0xc3, 0x4f, 0x0f, 0xfa, 0xb3, 0x46, 0xc3, 0x11, 0x0c, 0xd4,
	0x82, 0x4a, 0xa7, 0xdc, 0x47, 0xe0, 0x8d, 0xbd, 0x89, 0xff, 0xb8, 0xbd, 0xf1, 0x0c, 0x0e, 0x6c,
	0x95, 0x48, 0x7a, 0xb6, 0xb4, 0x08, 0xfe, 0xb3, 0xf8, 0x0d, 0xf0, 0x1c, 0x80, 0x8f, 0x7b, 0x55,
	0x28, 0x17, 0xf8, 0x2c, 0x77, 0x08, 0x8e, 0xe1, 0xd0, 0x99, 0x24, 0xcb, 0x94, 0xe4, 0xfc, 0x1e,
	0x1b, 0xba, 0x08, 0x43, 0x18, 0xb6, 0x67, 0xd3, 0xb1, 0xcf, 0x96, 0x1f, 0x0c, 0x27, 0x70, 0xfc,
	0x90, 0x65, 0x2b, 0x55, 0xd2, 0x53, 0x62, 0x5f, 0xb9, 0xa9, 0xc7, 0xb6, 0xdf, 0x18, 0x2f, 0xe0,
	0xa4, 0x83, 0x9a, 0xc6, 0x3e, 0x5b, 0x77, 0xf8, 0xf5, 0x3b, 0x1c, 0xb5, 0x03, 0xcc, 0x9b, 0x51,
	0x70, 0x0a, 0x7e, 0x4e, 0x0e, 0x4f, 0xa3, 0xcd, 0x4a, 0x51, 0x6b, 0x18, 0xed, 0xa2, 0xf0, 0x1f,
	0xde, 0xc2, 0xd0, 0x92, 0x9b, 0x6f, 0xc7, 0xf8, 0x63, 0x6e, 0x76, 0xf7, 0x12, 0xe7, 0xca, 0x2d,
	0xd7, 0x69, 0x24, 0x75, 0x21, 0xea, 0xba, 0x5e, 0x9a, 0xab, 0x38, 0xbe, 0x14, 0x52, 0x17, 0x85,
	0x2e, 0xa7, 0xb9, 0xa9, 0xa4, 0xc8, 0xb5, 0xd8, 0x24, 0x45, 0xf7, 0x8f, 0x69, 0x8f, 0x1f, 0x79,
	0xf3, 0x15, 0x00, 0x00, 0xff, 0xff, 0x06, 0x23, 0xd1, 0x4e, 0xde, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BalanceServiceClient is the client API for BalanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BalanceServiceClient interface {
	Get(ctx context.Context, in *Balance, opts ...grpc.CallOption) (*Balance, error)
	SetSpaceUsed(ctx context.Context, in *Balance, opts ...grpc.CallOption) (*Balance, error)
}

type balanceServiceClient struct {
	cc *grpc.ClientConn
}

func NewBalanceServiceClient(cc *grpc.ClientConn) BalanceServiceClient {
	return &balanceServiceClient{cc}
}

func (c *balanceServiceClient) Get(ctx context.Context, in *Balance, opts ...grpc.CallOption) (*Balance, error) {
	out := new(Balance)
	err := c.cc.Invoke(ctx, "/services.BalanceService/get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceServiceClient) SetSpaceUsed(ctx context.Context, in *Balance, opts ...grpc.CallOption) (*Balance, error) {
	out := new(Balance)
	err := c.cc.Invoke(ctx, "/services.BalanceService/setSpaceUsed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BalanceServiceServer is the server API for BalanceService service.
type BalanceServiceServer interface {
	Get(context.Context, *Balance) (*Balance, error)
	SetSpaceUsed(context.Context, *Balance) (*Balance, error)
}

// UnimplementedBalanceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBalanceServiceServer struct {
}

func (*UnimplementedBalanceServiceServer) Get(ctx context.Context, req *Balance) (*Balance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedBalanceServiceServer) SetSpaceUsed(ctx context.Context, req *Balance) (*Balance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSpaceUsed not implemented")
}

func RegisterBalanceServiceServer(s *grpc.Server, srv BalanceServiceServer) {
	s.RegisterService(&_BalanceService_serviceDesc, srv)
}

func _BalanceService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Balance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.BalanceService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServiceServer).Get(ctx, req.(*Balance))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceService_SetSpaceUsed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Balance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServiceServer).SetSpaceUsed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.BalanceService/SetSpaceUsed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServiceServer).SetSpaceUsed(ctx, req.(*Balance))
	}
	return interceptor(ctx, in, info, handler)
}

var _BalanceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.BalanceService",
	HandlerType: (*BalanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "get",
			Handler:    _BalanceService_Get_Handler,
		},
		{
			MethodName: "setSpaceUsed",
			Handler:    _BalanceService_SetSpaceUsed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/balance.proto",
}
