// Code generated by protoc-gen-go. DO NOT EDIT.
// source: system/system.proto

package sysinfo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SystemInfo struct {
	RequestTime          int64    `protobuf:"varint,1,opt,name=request_time,json=requestTime,proto3" json:"request_time,omitempty"`
	RequestUser          string   `protobuf:"bytes,2,opt,name=request_user,json=requestUser,proto3" json:"request_user,omitempty"`
	ServerName           string   `protobuf:"bytes,3,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	ServerTime           int64    `protobuf:"varint,4,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	AccessCount          int64    `protobuf:"varint,5,opt,name=access_count,json=accessCount,proto3" json:"access_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemInfo) Reset()         { *m = SystemInfo{} }
func (m *SystemInfo) String() string { return proto.CompactTextString(m) }
func (*SystemInfo) ProtoMessage()    {}
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_746080b643370b3b, []int{0}
}

func (m *SystemInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemInfo.Unmarshal(m, b)
}
func (m *SystemInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemInfo.Marshal(b, m, deterministic)
}
func (m *SystemInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemInfo.Merge(m, src)
}
func (m *SystemInfo) XXX_Size() int {
	return xxx_messageInfo_SystemInfo.Size(m)
}
func (m *SystemInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SystemInfo proto.InternalMessageInfo

func (m *SystemInfo) GetRequestTime() int64 {
	if m != nil {
		return m.RequestTime
	}
	return 0
}

func (m *SystemInfo) GetRequestUser() string {
	if m != nil {
		return m.RequestUser
	}
	return ""
}

func (m *SystemInfo) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *SystemInfo) GetServerTime() int64 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

func (m *SystemInfo) GetAccessCount() int64 {
	if m != nil {
		return m.AccessCount
	}
	return 0
}

type ClientInfo struct {
	ClientName           string   `protobuf:"bytes,1,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientInfo) Reset()         { *m = ClientInfo{} }
func (m *ClientInfo) String() string { return proto.CompactTextString(m) }
func (*ClientInfo) ProtoMessage()    {}
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_746080b643370b3b, []int{1}
}

func (m *ClientInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientInfo.Unmarshal(m, b)
}
func (m *ClientInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientInfo.Marshal(b, m, deterministic)
}
func (m *ClientInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientInfo.Merge(m, src)
}
func (m *ClientInfo) XXX_Size() int {
	return xxx_messageInfo_ClientInfo.Size(m)
}
func (m *ClientInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClientInfo proto.InternalMessageInfo

func (m *ClientInfo) GetClientName() string {
	if m != nil {
		return m.ClientName
	}
	return ""
}

func init() {
	proto.RegisterType((*SystemInfo)(nil), "services.SystemInfo")
	proto.RegisterType((*ClientInfo)(nil), "services.ClientInfo")
}

func init() { proto.RegisterFile("system/system.proto", fileDescriptor_746080b643370b3b) }

var fileDescriptor_746080b643370b3b = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0x87, 0x31, 0x85, 0x0a, 0xae, 0x2c, 0x18, 0x86, 0x88, 0xa5, 0x25, 0x53, 0x97, 0xc6, 0xfc,
	0x91, 0x90, 0x2a, 0xc4, 0x42, 0x27, 0x84, 0xc4, 0x40, 0x61, 0x61, 0x89, 0x52, 0xeb, 0x9a, 0x5a,
	0xc2, 0x76, 0xf1, 0x39, 0x48, 0xe4, 0xc5, 0x78, 0x3d, 0x14, 0xbb, 0x21, 0x99, 0xa2, 0x7c, 0xfe,
	0x9d, 0xbf, 0x3b, 0x1f, 0x9c, 0xd1, 0x0f, 0x79, 0xd4, 0x22, 0x7e, 0xb2, 0xad, 0xb3, 0xde, 0xf2,
	0x23, 0x42, 0xf7, 0xad, 0x24, 0x52, 0xfa, 0xcb, 0x00, 0x96, 0xe1, 0xe8, 0xc9, 0xac, 0x2d, 0xbf,
	0x84, 0x13, 0x87, 0x5f, 0x15, 0x92, 0xcf, 0xbd, 0xd2, 0x98, 0xb0, 0x09, 0x9b, 0x0e, 0x5e, 0x47,
	0x3b, 0xf6, 0xa6, 0x34, 0xf6, 0x23, 0x15, 0xa1, 0x4b, 0xf6, 0x27, 0x6c, 0x7a, 0xfc, 0x1f, 0x79,
	0x27, 0x74, 0x7c, 0x0c, 0xa3, 0x46, 0x80, 0x2e, 0x37, 0x85, 0xc6, 0x64, 0x10, 0x12, 0x10, 0xd1,
	0x4b, 0xa1, 0xb1, 0x17, 0x08, 0x96, 0x83, 0x60, 0xd9, 0x05, 0x5a, 0x49, 0x21, 0x25, 0x12, 0xe5,
	0xd2, 0x56, 0xc6, 0x27, 0x87, 0xb1, 0x8f, 0xc8, 0x16, 0x0d, 0x4a, 0x67, 0x00, 0x8b, 0x4f, 0x85,
	0xc6, 0x87, 0xc6, 0xc7, 0x30, 0x92, 0xe1, 0x2f, 0x2a, 0x59, 0x54, 0x46, 0xd4, 0x28, 0x6f, 0x9e,
	0xe1, 0xb4, 0x9b, 0x73, 0x19, 0xc7, 0xe7, 0x77, 0x30, 0x94, 0x0e, 0x0b, 0x8f, 0xfc, 0x3c, 0x6b,
	0x9f, 0x24, 0xeb, 0x6e, 0xbd, 0xe8, 0xd1, 0xae, 0x38, 0xdd, 0x7b, 0x7c, 0xf8, 0xb8, 0x2f, 0x95,
	0xdf, 0x54, 0xab, 0x4c, 0x5a, 0x2d, 0xea, 0xba, 0xde, 0xb8, 0xeb, 0xf9, 0xfc, 0x4a, 0x48, 0xab,
	0xb5, 0x35, 0xb3, 0xd2, 0x6d, 0xa5, 0x28, 0xad, 0x68, 0x8b, 0x45, 0xb7, 0x03, 0x65, 0xd6, 0x76,
	0x35, 0x0c, 0x5b, 0xb8, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x70, 0x8f, 0x5f, 0x9c, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SystemInfoServiceClient is the client API for SystemInfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SystemInfoServiceClient interface {
	Create(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*SystemInfo, error)
}

type systemInfoServiceClient struct {
	cc *grpc.ClientConn
}

func NewSystemInfoServiceClient(cc *grpc.ClientConn) SystemInfoServiceClient {
	return &systemInfoServiceClient{cc}
}

func (c *systemInfoServiceClient) Create(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*SystemInfo, error) {
	out := new(SystemInfo)
	err := c.cc.Invoke(ctx, "/services.SystemInfoService/create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemInfoServiceServer is the server API for SystemInfoService service.
type SystemInfoServiceServer interface {
	Create(context.Context, *ClientInfo) (*SystemInfo, error)
}

// UnimplementedSystemInfoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSystemInfoServiceServer struct {
}

func (*UnimplementedSystemInfoServiceServer) Create(ctx context.Context, req *ClientInfo) (*SystemInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterSystemInfoServiceServer(s *grpc.Server, srv SystemInfoServiceServer) {
	s.RegisterService(&_SystemInfoService_serviceDesc, srv)
}

func _SystemInfoService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemInfoServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.SystemInfoService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemInfoServiceServer).Create(ctx, req.(*ClientInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _SystemInfoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.SystemInfoService",
	HandlerType: (*SystemInfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "create",
			Handler:    _SystemInfoService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "system/system.proto",
}
