// Code generated by protoc-gen-go. DO NOT EDIT.
// source: store/cloudstore.proto

package cloudstore

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "github.com/zzzhr1990/common-grpc/go/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CloudStore struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Mime                 string   `protobuf:"bytes,3,opt,name=mime,proto3" json:"mime,omitempty"`
	UploadUser           int64    `protobuf:"varint,4,opt,name=uploadUser,proto3" json:"uploadUser,omitempty"`
	Ctime                int64    `protobuf:"varint,5,opt,name=ctime,proto3" json:"ctime,omitempty"`
	OriginalaFilename    string   `protobuf:"bytes,6,opt,name=originalaFilename,proto3" json:"originalaFilename,omitempty"`
	Store                int32    `protobuf:"varint,7,opt,name=store,proto3" json:"store,omitempty"`
	Key                  string   `protobuf:"bytes,8,opt,name=key,proto3" json:"key,omitempty"`
	Type                 int32    `protobuf:"varint,9,opt,name=type,proto3" json:"type,omitempty"`
	Preview              bool     `protobuf:"varint,10,opt,name=preview,proto3" json:"preview,omitempty"`
	PreviewType          int32    `protobuf:"varint,11,opt,name=previewType,proto3" json:"previewType,omitempty"`
	Flag                 int32    `protobuf:"varint,12,opt,name=flag,proto3" json:"flag,omitempty"`
	DownloadAddress      string   `protobuf:"bytes,13,opt,name=downloadAddress,proto3" json:"downloadAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloudStore) Reset()         { *m = CloudStore{} }
func (m *CloudStore) String() string { return proto.CompactTextString(m) }
func (*CloudStore) ProtoMessage()    {}
func (*CloudStore) Descriptor() ([]byte, []int) {
	return fileDescriptor_e406880dd1e5ea92, []int{0}
}

func (m *CloudStore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloudStore.Unmarshal(m, b)
}
func (m *CloudStore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloudStore.Marshal(b, m, deterministic)
}
func (m *CloudStore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloudStore.Merge(m, src)
}
func (m *CloudStore) XXX_Size() int {
	return xxx_messageInfo_CloudStore.Size(m)
}
func (m *CloudStore) XXX_DiscardUnknown() {
	xxx_messageInfo_CloudStore.DiscardUnknown(m)
}

var xxx_messageInfo_CloudStore proto.InternalMessageInfo

func (m *CloudStore) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *CloudStore) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *CloudStore) GetMime() string {
	if m != nil {
		return m.Mime
	}
	return ""
}

func (m *CloudStore) GetUploadUser() int64 {
	if m != nil {
		return m.UploadUser
	}
	return 0
}

func (m *CloudStore) GetCtime() int64 {
	if m != nil {
		return m.Ctime
	}
	return 0
}

func (m *CloudStore) GetOriginalaFilename() string {
	if m != nil {
		return m.OriginalaFilename
	}
	return ""
}

func (m *CloudStore) GetStore() int32 {
	if m != nil {
		return m.Store
	}
	return 0
}

func (m *CloudStore) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CloudStore) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *CloudStore) GetPreview() bool {
	if m != nil {
		return m.Preview
	}
	return false
}

func (m *CloudStore) GetPreviewType() int32 {
	if m != nil {
		return m.PreviewType
	}
	return 0
}

func (m *CloudStore) GetFlag() int32 {
	if m != nil {
		return m.Flag
	}
	return 0
}

func (m *CloudStore) GetDownloadAddress() string {
	if m != nil {
		return m.DownloadAddress
	}
	return ""
}

type CloudStoreList struct {
	Data                 []*CloudStore `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CloudStoreList) Reset()         { *m = CloudStoreList{} }
func (m *CloudStoreList) String() string { return proto.CompactTextString(m) }
func (*CloudStoreList) ProtoMessage()    {}
func (*CloudStoreList) Descriptor() ([]byte, []int) {
	return fileDescriptor_e406880dd1e5ea92, []int{1}
}

func (m *CloudStoreList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloudStoreList.Unmarshal(m, b)
}
func (m *CloudStoreList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloudStoreList.Marshal(b, m, deterministic)
}
func (m *CloudStoreList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloudStoreList.Merge(m, src)
}
func (m *CloudStoreList) XXX_Size() int {
	return xxx_messageInfo_CloudStoreList.Size(m)
}
func (m *CloudStoreList) XXX_DiscardUnknown() {
	xxx_messageInfo_CloudStoreList.DiscardUnknown(m)
}

var xxx_messageInfo_CloudStoreList proto.InternalMessageInfo

func (m *CloudStoreList) GetData() []*CloudStore {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*CloudStore)(nil), "services.CloudStore")
	proto.RegisterType((*CloudStoreList)(nil), "services.CloudStoreList")
}

func init() { proto.RegisterFile("store/cloudstore.proto", fileDescriptor_e406880dd1e5ea92) }

var fileDescriptor_e406880dd1e5ea92 = []byte{
	// 465 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0x97, 0xa5, 0xed, 0xda, 0x53, 0xfe, 0xcd, 0x9a, 0x86, 0x95, 0x0b, 0x14, 0xe5, 0x2a,
	0x17, 0xd0, 0xc0, 0x26, 0x21, 0x75, 0x12, 0x42, 0x50, 0x86, 0x84, 0x40, 0x42, 0x4a, 0xe1, 0x86,
	0x1b, 0xe4, 0x26, 0x07, 0xc7, 0x22, 0x89, 0x23, 0xdb, 0xdd, 0x94, 0xbe, 0x1d, 0xaf, 0xc2, 0x93,
	0x20, 0x3b, 0xad, 0x3a, 0x46, 0x77, 0x51, 0xae, 0xfa, 0xf9, 0xf3, 0xf7, 0x3b, 0x3d, 0x27, 0xd6,
	0x81, 0x53, 0x6d, 0xa4, 0xc2, 0x24, 0x2b, 0xe5, 0x32, 0x77, 0x72, 0xd2, 0x28, 0x69, 0x24, 0x19,
	0x6a, 0x54, 0x57, 0x22, 0x43, 0x1d, 0x04, 0x99, 0xac, 0x2a, 0x59, 0x27, 0xdd, 0xcf, 0x77, 0xac,
	0x8d, 0x30, 0x6d, 0x97, 0x8a, 0x7e, 0x1f, 0x02, 0xcc, 0x2c, 0x3a, 0xb7, 0x28, 0x21, 0xd0, 0x2b,
	0x98, 0x2e, 0xa8, 0x17, 0x7a, 0xf1, 0x28, 0x75, 0xda, 0x7a, 0x5a, 0xac, 0x90, 0x1e, 0x86, 0x5e,
	0xec, 0xa7, 0x4e, 0x5b, 0xaf, 0x12, 0x15, 0x52, 0xbf, 0xcb, 0x59, 0x4d, 0x9e, 0x00, 0x2c, 0x9b,
	0x52, 0xb2, 0xfc, 0xab, 0x46, 0x45, 0x7b, 0x2e, 0x7d, 0xc3, 0x21, 0x27, 0xd0, 0xcf, 0x8c, 0x85,
	0xfa, 0xee, 0xaa, 0x3b, 0x90, 0xa7, 0x70, 0x2c, 0x95, 0xe0, 0xa2, 0x66, 0x25, 0x7b, 0x2f, 0x4a,
	0xac, 0x59, 0x85, 0x74, 0xe0, 0xca, 0xfe, 0x7b, 0x61, 0x6b, 0xb8, 0x19, 0xe9, 0x51, 0xe8, 0xc5,
	0xfd, 0xb4, 0x3b, 0x90, 0x47, 0xe0, 0xff, 0xc4, 0x96, 0x0e, 0x1d, 0x65, 0xa5, 0xed, 0xcf, 0xb4,
	0x0d, 0xd2, 0x91, 0x8b, 0x39, 0x4d, 0x28, 0x1c, 0x35, 0x0a, 0xaf, 0x04, 0x5e, 0x53, 0x08, 0xbd,
	0x78, 0x98, 0x6e, 0x8e, 0x24, 0x84, 0xf1, 0x5a, 0x7e, 0xb1, 0xd0, 0xd8, 0x41, 0x37, 0x2d, 0x5b,
	0xef, 0x47, 0xc9, 0x38, 0xbd, 0xd7, 0xd5, 0xb3, 0x9a, 0xc4, 0xf0, 0x30, 0x97, 0xd7, 0xb5, 0x9d,
	0xef, 0x4d, 0x9e, 0x2b, 0xd4, 0x9a, 0xde, 0x77, 0x1d, 0xdc, 0xb6, 0xa3, 0x0b, 0x78, 0xb0, 0xfd,
	0xc6, 0x9f, 0x84, 0x36, 0x24, 0x86, 0x5e, 0xce, 0x0c, 0xa3, 0x5e, 0xe8, 0xc7, 0xe3, 0xb3, 0x93,
	0xc9, 0xe6, 0xad, 0x26, 0xdb, 0x5c, 0xea, 0x12, 0x67, 0xbf, 0x7c, 0x38, 0xde, 0x9a, 0xf3, 0x2e,
	0x47, 0x5e, 0xc2, 0x20, 0x53, 0xc8, 0x0c, 0x92, 0x9d, 0x6c, 0xb0, 0xd3, 0x8d, 0x0e, 0xc8, 0x14,
	0x46, 0x46, 0xb5, 0xb3, 0xff, 0x41, 0x67, 0x30, 0x5e, 0x30, 0x93, 0x15, 0x6b, 0x98, 0xee, 0x8a,
	0xd9, 0xd9, 0x82, 0x3b, 0x6f, 0xa2, 0x03, 0x72, 0x0e, 0x3e, 0x47, 0xb3, 0xe7, 0x3f, 0xdb, 0x61,
	0x0b, 0x56, 0xf3, 0x7d, 0x3b, 0xbe, 0x00, 0xe0, 0x68, 0x3e, 0xab, 0xcb, 0xaa, 0x31, 0xed, 0x9e,
	0xec, 0x47, 0x78, 0xcc, 0xd1, 0x7c, 0xa8, 0x6b, 0x54, 0xef, 0xfe, 0x7e, 0x4d, 0x72, 0xba, 0x45,
	0xe6, 0x46, 0x89, 0x9a, 0x5f, 0xba, 0x85, 0x0a, 0xee, 0xf0, 0xa3, 0x83, 0xb7, 0xaf, 0xbf, 0xbd,
	0xe2, 0xc2, 0x14, 0xcb, 0xc5, 0x24, 0x93, 0x55, 0xb2, 0x5a, 0xad, 0x0a, 0xf5, 0x62, 0x3a, 0x7d,
	0xbe, 0x5e, 0xc8, 0x67, 0x5c, 0x35, 0x59, 0xc2, 0x65, 0xb2, 0xc1, 0x93, 0xdb, 0x1b, 0xbd, 0x18,
	0xb8, 0x65, 0x3d, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x09, 0xd6, 0x62, 0xec, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CloudStoreServiceClient is the client API for CloudStoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CloudStoreServiceClient interface {
	Create(ctx context.Context, in *CloudStore, opts ...grpc.CallOption) (*CloudStore, error)
	TryCreate(ctx context.Context, in *CloudStore, opts ...grpc.CallOption) (*CloudStore, error)
	BatchCreate(ctx context.Context, in *CloudStoreList, opts ...grpc.CallOption) (*CloudStoreList, error)
	Get(ctx context.Context, in *CloudStore, opts ...grpc.CallOption) (*CloudStore, error)
	Change(ctx context.Context, in *CloudStore, opts ...grpc.CallOption) (*CloudStore, error)
	// rpc batchGet (CloudStoreList) returns (CloudStoreList) {}
	// rpc batchGetByHash (StringListEntity) returns (CloudStoreList) {}
	GetOrEmpty(ctx context.Context, in *CloudStore, opts ...grpc.CallOption) (*CloudStore, error)
	GetInnerDownloadAddress(ctx context.Context, in *common.StringEntity, opts ...grpc.CallOption) (*common.StringEntity, error)
}

type cloudStoreServiceClient struct {
	cc *grpc.ClientConn
}

func NewCloudStoreServiceClient(cc *grpc.ClientConn) CloudStoreServiceClient {
	return &cloudStoreServiceClient{cc}
}

func (c *cloudStoreServiceClient) Create(ctx context.Context, in *CloudStore, opts ...grpc.CallOption) (*CloudStore, error) {
	out := new(CloudStore)
	err := c.cc.Invoke(ctx, "/services.CloudStoreService/create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudStoreServiceClient) TryCreate(ctx context.Context, in *CloudStore, opts ...grpc.CallOption) (*CloudStore, error) {
	out := new(CloudStore)
	err := c.cc.Invoke(ctx, "/services.CloudStoreService/tryCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudStoreServiceClient) BatchCreate(ctx context.Context, in *CloudStoreList, opts ...grpc.CallOption) (*CloudStoreList, error) {
	out := new(CloudStoreList)
	err := c.cc.Invoke(ctx, "/services.CloudStoreService/batchCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudStoreServiceClient) Get(ctx context.Context, in *CloudStore, opts ...grpc.CallOption) (*CloudStore, error) {
	out := new(CloudStore)
	err := c.cc.Invoke(ctx, "/services.CloudStoreService/get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudStoreServiceClient) Change(ctx context.Context, in *CloudStore, opts ...grpc.CallOption) (*CloudStore, error) {
	out := new(CloudStore)
	err := c.cc.Invoke(ctx, "/services.CloudStoreService/change", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudStoreServiceClient) GetOrEmpty(ctx context.Context, in *CloudStore, opts ...grpc.CallOption) (*CloudStore, error) {
	out := new(CloudStore)
	err := c.cc.Invoke(ctx, "/services.CloudStoreService/getOrEmpty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudStoreServiceClient) GetInnerDownloadAddress(ctx context.Context, in *common.StringEntity, opts ...grpc.CallOption) (*common.StringEntity, error) {
	out := new(common.StringEntity)
	err := c.cc.Invoke(ctx, "/services.CloudStoreService/getInnerDownloadAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudStoreServiceServer is the server API for CloudStoreService service.
type CloudStoreServiceServer interface {
	Create(context.Context, *CloudStore) (*CloudStore, error)
	TryCreate(context.Context, *CloudStore) (*CloudStore, error)
	BatchCreate(context.Context, *CloudStoreList) (*CloudStoreList, error)
	Get(context.Context, *CloudStore) (*CloudStore, error)
	Change(context.Context, *CloudStore) (*CloudStore, error)
	// rpc batchGet (CloudStoreList) returns (CloudStoreList) {}
	// rpc batchGetByHash (StringListEntity) returns (CloudStoreList) {}
	GetOrEmpty(context.Context, *CloudStore) (*CloudStore, error)
	GetInnerDownloadAddress(context.Context, *common.StringEntity) (*common.StringEntity, error)
}

// UnimplementedCloudStoreServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCloudStoreServiceServer struct {
}

func (*UnimplementedCloudStoreServiceServer) Create(ctx context.Context, req *CloudStore) (*CloudStore, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedCloudStoreServiceServer) TryCreate(ctx context.Context, req *CloudStore) (*CloudStore, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TryCreate not implemented")
}
func (*UnimplementedCloudStoreServiceServer) BatchCreate(ctx context.Context, req *CloudStoreList) (*CloudStoreList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchCreate not implemented")
}
func (*UnimplementedCloudStoreServiceServer) Get(ctx context.Context, req *CloudStore) (*CloudStore, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedCloudStoreServiceServer) Change(ctx context.Context, req *CloudStore) (*CloudStore, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Change not implemented")
}
func (*UnimplementedCloudStoreServiceServer) GetOrEmpty(ctx context.Context, req *CloudStore) (*CloudStore, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrEmpty not implemented")
}
func (*UnimplementedCloudStoreServiceServer) GetInnerDownloadAddress(ctx context.Context, req *common.StringEntity) (*common.StringEntity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInnerDownloadAddress not implemented")
}

func RegisterCloudStoreServiceServer(s *grpc.Server, srv CloudStoreServiceServer) {
	s.RegisterService(&_CloudStoreService_serviceDesc, srv)
}

func _CloudStoreService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloudStore)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudStoreServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.CloudStoreService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudStoreServiceServer).Create(ctx, req.(*CloudStore))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudStoreService_TryCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloudStore)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudStoreServiceServer).TryCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.CloudStoreService/TryCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudStoreServiceServer).TryCreate(ctx, req.(*CloudStore))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudStoreService_BatchCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloudStoreList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudStoreServiceServer).BatchCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.CloudStoreService/BatchCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudStoreServiceServer).BatchCreate(ctx, req.(*CloudStoreList))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudStoreService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloudStore)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudStoreServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.CloudStoreService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudStoreServiceServer).Get(ctx, req.(*CloudStore))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudStoreService_Change_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloudStore)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudStoreServiceServer).Change(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.CloudStoreService/Change",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudStoreServiceServer).Change(ctx, req.(*CloudStore))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudStoreService_GetOrEmpty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloudStore)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudStoreServiceServer).GetOrEmpty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.CloudStoreService/GetOrEmpty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudStoreServiceServer).GetOrEmpty(ctx, req.(*CloudStore))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudStoreService_GetInnerDownloadAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.StringEntity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudStoreServiceServer).GetInnerDownloadAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.CloudStoreService/GetInnerDownloadAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudStoreServiceServer).GetInnerDownloadAddress(ctx, req.(*common.StringEntity))
	}
	return interceptor(ctx, in, info, handler)
}

var _CloudStoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.CloudStoreService",
	HandlerType: (*CloudStoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "create",
			Handler:    _CloudStoreService_Create_Handler,
		},
		{
			MethodName: "tryCreate",
			Handler:    _CloudStoreService_TryCreate_Handler,
		},
		{
			MethodName: "batchCreate",
			Handler:    _CloudStoreService_BatchCreate_Handler,
		},
		{
			MethodName: "get",
			Handler:    _CloudStoreService_Get_Handler,
		},
		{
			MethodName: "change",
			Handler:    _CloudStoreService_Change_Handler,
		},
		{
			MethodName: "getOrEmpty",
			Handler:    _CloudStoreService_GetOrEmpty_Handler,
		},
		{
			MethodName: "getInnerDownloadAddress",
			Handler:    _CloudStoreService_GetInnerDownloadAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "store/cloudstore.proto",
}
