// Code generated by protoc-gen-go. DO NOT EDIT.
// source: store/cloudstore.proto

package cloudstore

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CloudStore struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Mime                 string   `protobuf:"bytes,3,opt,name=mime,proto3" json:"mime,omitempty"`
	UploadUser           int64    `protobuf:"varint,4,opt,name=upload_user,json=uploadUser,proto3" json:"upload_user,omitempty"`
	Ctime                int64    `protobuf:"varint,5,opt,name=ctime,proto3" json:"ctime,omitempty"`
	OriginalalFilename   string   `protobuf:"bytes,6,opt,name=originalal_filename,json=originalalFilename,proto3" json:"originalal_filename,omitempty"`
	Store                int32    `protobuf:"varint,7,opt,name=store,proto3" json:"store,omitempty"`
	Key                  string   `protobuf:"bytes,8,opt,name=key,proto3" json:"key,omitempty"`
	ColdKey              string   `protobuf:"bytes,9,opt,name=cold_key,json=coldKey,proto3" json:"cold_key,omitempty"`
	Type                 int32    `protobuf:"varint,10,opt,name=type,proto3" json:"type,omitempty"`
	Preview              bool     `protobuf:"varint,11,opt,name=preview,proto3" json:"preview,omitempty"`
	PreviewType          int32    `protobuf:"varint,12,opt,name=preview_type,json=previewType,proto3" json:"preview_type,omitempty"`
	Flag                 int32    `protobuf:"varint,13,opt,name=flag,proto3" json:"flag,omitempty"`
	Status               int32    `protobuf:"varint,14,opt,name=status,proto3" json:"status,omitempty"`
	FetchTime            int64    `protobuf:"varint,15,opt,name=fetch_time,json=fetchTime,proto3" json:"fetch_time,omitempty"`
	Md5                  string   `protobuf:"bytes,16,opt,name=md5,proto3" json:"md5,omitempty"`
	Sha1                 string   `protobuf:"bytes,17,opt,name=sha1,proto3" json:"sha1,omitempty"`
	DownloadAddress      string   `protobuf:"bytes,18,opt,name=download_address,json=downloadAddress,proto3" json:"download_address,omitempty"`
	Ref                  int64    `protobuf:"varint,19,opt,name=ref,proto3" json:"ref,omitempty"`
	LastDown             int64    `protobuf:"varint,20,opt,name=last_down,json=lastDown,proto3" json:"last_down,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloudStore) Reset()         { *m = CloudStore{} }
func (m *CloudStore) String() string { return proto.CompactTextString(m) }
func (*CloudStore) ProtoMessage()    {}
func (*CloudStore) Descriptor() ([]byte, []int) {
	return fileDescriptor_e406880dd1e5ea92, []int{0}
}

func (m *CloudStore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloudStore.Unmarshal(m, b)
}
func (m *CloudStore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloudStore.Marshal(b, m, deterministic)
}
func (m *CloudStore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloudStore.Merge(m, src)
}
func (m *CloudStore) XXX_Size() int {
	return xxx_messageInfo_CloudStore.Size(m)
}
func (m *CloudStore) XXX_DiscardUnknown() {
	xxx_messageInfo_CloudStore.DiscardUnknown(m)
}

var xxx_messageInfo_CloudStore proto.InternalMessageInfo

func (m *CloudStore) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *CloudStore) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *CloudStore) GetMime() string {
	if m != nil {
		return m.Mime
	}
	return ""
}

func (m *CloudStore) GetUploadUser() int64 {
	if m != nil {
		return m.UploadUser
	}
	return 0
}

func (m *CloudStore) GetCtime() int64 {
	if m != nil {
		return m.Ctime
	}
	return 0
}

func (m *CloudStore) GetOriginalalFilename() string {
	if m != nil {
		return m.OriginalalFilename
	}
	return ""
}

func (m *CloudStore) GetStore() int32 {
	if m != nil {
		return m.Store
	}
	return 0
}

func (m *CloudStore) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CloudStore) GetColdKey() string {
	if m != nil {
		return m.ColdKey
	}
	return ""
}

func (m *CloudStore) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *CloudStore) GetPreview() bool {
	if m != nil {
		return m.Preview
	}
	return false
}

func (m *CloudStore) GetPreviewType() int32 {
	if m != nil {
		return m.PreviewType
	}
	return 0
}

func (m *CloudStore) GetFlag() int32 {
	if m != nil {
		return m.Flag
	}
	return 0
}

func (m *CloudStore) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CloudStore) GetFetchTime() int64 {
	if m != nil {
		return m.FetchTime
	}
	return 0
}

func (m *CloudStore) GetMd5() string {
	if m != nil {
		return m.Md5
	}
	return ""
}

func (m *CloudStore) GetSha1() string {
	if m != nil {
		return m.Sha1
	}
	return ""
}

func (m *CloudStore) GetDownloadAddress() string {
	if m != nil {
		return m.DownloadAddress
	}
	return ""
}

func (m *CloudStore) GetRef() int64 {
	if m != nil {
		return m.Ref
	}
	return 0
}

func (m *CloudStore) GetLastDown() int64 {
	if m != nil {
		return m.LastDown
	}
	return 0
}

type CloudStoreList struct {
	Data                 []*CloudStore `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CloudStoreList) Reset()         { *m = CloudStoreList{} }
func (m *CloudStoreList) String() string { return proto.CompactTextString(m) }
func (*CloudStoreList) ProtoMessage()    {}
func (*CloudStoreList) Descriptor() ([]byte, []int) {
	return fileDescriptor_e406880dd1e5ea92, []int{1}
}

func (m *CloudStoreList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloudStoreList.Unmarshal(m, b)
}
func (m *CloudStoreList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloudStoreList.Marshal(b, m, deterministic)
}
func (m *CloudStoreList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloudStoreList.Merge(m, src)
}
func (m *CloudStoreList) XXX_Size() int {
	return xxx_messageInfo_CloudStoreList.Size(m)
}
func (m *CloudStoreList) XXX_DiscardUnknown() {
	xxx_messageInfo_CloudStoreList.DiscardUnknown(m)
}

var xxx_messageInfo_CloudStoreList proto.InternalMessageInfo

func (m *CloudStoreList) GetData() []*CloudStore {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*CloudStore)(nil), "services.CloudStore")
	proto.RegisterType((*CloudStoreList)(nil), "services.CloudStoreList")
}

func init() { proto.RegisterFile("store/cloudstore.proto", fileDescriptor_e406880dd1e5ea92) }

var fileDescriptor_e406880dd1e5ea92 = []byte{
	// 532 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0x5e, 0x96, 0xae, 0x4b, 0x5f, 0xc7, 0xd6, 0xbd, 0x55, 0x93, 0x19, 0x42, 0x94, 0x9e, 0xc2,
	0x81, 0x86, 0x6d, 0xda, 0xa4, 0x81, 0x10, 0xd0, 0x21, 0x76, 0x80, 0x53, 0xd7, 0x5e, 0xb8, 0x44,
	0x5e, 0xe2, 0x36, 0xd1, 0x92, 0x38, 0xb2, 0xdd, 0x55, 0xed, 0x9f, 0xe0, 0x07, 0x73, 0x41, 0x7e,
	0x69, 0x55, 0x84, 0xca, 0xa1, 0xb7, 0xef, 0x7d, 0xef, 0xfb, 0x9e, 0xed, 0x2f, 0x8e, 0xe1, 0x54,
	0x1b, 0xa9, 0x44, 0x10, 0x65, 0x72, 0x1a, 0x13, 0xec, 0x95, 0x4a, 0x1a, 0x89, 0x9e, 0x16, 0xea,
	0x29, 0x8d, 0x84, 0xee, 0xfe, 0xaa, 0x01, 0xdc, 0xda, 0xf6, 0xbd, 0x6d, 0x23, 0x42, 0x2d, 0xe1,
	0x3a, 0x61, 0x4e, 0xc7, 0xf1, 0x1b, 0x03, 0xc2, 0x96, 0xd3, 0xe9, 0x42, 0xb0, 0xdd, 0x8e, 0xe3,
	0xbb, 0x03, 0xc2, 0x96, 0xcb, 0xd3, 0x5c, 0x30, 0xb7, 0xd2, 0x59, 0x8c, 0xaf, 0xa0, 0x39, 0x2d,
	0x33, 0xc9, 0xe3, 0x70, 0xaa, 0x85, 0x62, 0x35, 0x92, 0x43, 0x45, 0x8d, 0xb4, 0x50, 0xd8, 0x86,
	0xbd, 0xc8, 0x58, 0xd7, 0x1e, 0xb5, 0xaa, 0x02, 0x03, 0x38, 0x91, 0x2a, 0x9d, 0xa4, 0x05, 0xcf,
	0x78, 0x16, 0x8e, 0xd3, 0x4c, 0x14, 0x3c, 0x17, 0xac, 0x4e, 0x93, 0x71, 0xdd, 0xfa, 0xb6, 0xec,
	0xd8, 0x31, 0x74, 0x16, 0xb6, 0xdf, 0x71, 0xfc, 0xbd, 0x41, 0x55, 0x60, 0x0b, 0xdc, 0x47, 0x31,
	0x67, 0x1e, 0xd9, 0x2c, 0xc4, 0xe7, 0xe0, 0x45, 0x32, 0x8b, 0x43, 0x4b, 0x37, 0x88, 0xde, 0xb7,
	0xf5, 0x77, 0x31, 0xb7, 0xdb, 0x37, 0xf3, 0x52, 0x30, 0xa0, 0x09, 0x84, 0x91, 0xc1, 0x7e, 0xa9,
	0xc4, 0x53, 0x2a, 0x66, 0xac, 0xd9, 0x71, 0x7c, 0x6f, 0xb0, 0x2a, 0xf1, 0x35, 0x1c, 0x2c, 0x61,
	0x48, 0xae, 0x03, 0x72, 0x35, 0x97, 0xdc, 0xd0, 0x9a, 0x11, 0x6a, 0xe3, 0x8c, 0x4f, 0xd8, 0xb3,
	0x6a, 0xa0, 0xc5, 0x78, 0x0a, 0x75, 0x6d, 0xb8, 0x99, 0x6a, 0x76, 0x48, 0xec, 0xb2, 0xc2, 0x97,
	0x00, 0x63, 0x61, 0xa2, 0x24, 0xa4, 0x2c, 0x8e, 0x28, 0x8b, 0x06, 0x31, 0x43, 0x9b, 0x47, 0x0b,
	0xdc, 0x3c, 0xbe, 0x62, 0xad, 0xea, 0x20, 0x79, 0x7c, 0x45, 0x1f, 0x20, 0xe1, 0xe7, 0xec, 0xb8,
	0x0a, 0xdb, 0x62, 0x7c, 0x03, 0xad, 0x58, 0xce, 0x0a, 0x8a, 0x9b, 0xc7, 0xb1, 0x12, 0x5a, 0x33,
	0xa4, 0xfe, 0xd1, 0x8a, 0xff, 0x52, 0xd1, 0x76, 0xa0, 0x12, 0x63, 0x76, 0x42, 0x0b, 0x59, 0x88,
	0x2f, 0xa0, 0x91, 0x71, 0x6d, 0x42, 0xab, 0x64, 0x6d, 0xe2, 0x3d, 0x4b, 0x7c, 0x95, 0xb3, 0xa2,
	0xfb, 0x1e, 0x0e, 0xd7, 0x17, 0xe2, 0x47, 0xaa, 0x0d, 0xfa, 0x50, 0x8b, 0xb9, 0xe1, 0xcc, 0xe9,
	0xb8, 0x7e, 0xf3, 0xa2, 0xdd, 0x5b, 0x5d, 0x9e, 0xde, 0x5a, 0x37, 0x20, 0xc5, 0xc5, 0xef, 0x5d,
	0x38, 0x5e, 0x93, 0xf7, 0x95, 0x0e, 0xaf, 0xa1, 0x7e, 0xab, 0x04, 0x37, 0x02, 0x37, 0x7a, 0xcf,
	0x36, 0xb2, 0xdd, 0x1d, 0xbc, 0x04, 0xf7, 0x4e, 0x98, 0x2d, 0x4d, 0xd7, 0x50, 0x1f, 0x95, 0xf1,
	0xf6, 0x8b, 0x7d, 0x06, 0xaf, 0xcf, 0x4d, 0x94, 0xd8, 0x15, 0xd9, 0x26, 0x8d, 0x8d, 0xe2, 0xec,
	0xbf, 0x9d, 0xee, 0x0e, 0xf6, 0x01, 0xef, 0x04, 0x65, 0xf8, 0x77, 0xfa, 0xdb, 0xed, 0xe2, 0x03,
	0x34, 0x47, 0xf4, 0xc3, 0x0c, 0xe5, 0xa3, 0x28, 0xb6, 0x33, 0xf7, 0x3f, 0xfd, 0xfc, 0x38, 0x49,
	0x4d, 0x32, 0x7d, 0xe8, 0x45, 0x32, 0x0f, 0x16, 0x8b, 0x45, 0xa2, 0xce, 0x6f, 0x6e, 0xde, 0x05,
	0x91, 0xcc, 0x73, 0x59, 0xbc, 0x9d, 0xa8, 0x32, 0x0a, 0x26, 0x32, 0x58, 0x99, 0x83, 0x7f, 0x1f,
	0x87, 0x87, 0x3a, 0xbd, 0x0e, 0x97, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x0b, 0xc9, 0xd1, 0x6a,
	0x37, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CloudStoreServiceClient is the client API for CloudStoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CloudStoreServiceClient interface {
	Create(ctx context.Context, in *CloudStore, opts ...grpc.CallOption) (*CloudStore, error)
	// rpc tryCreate (CloudStore) returns (CloudStore) {}
	// rpc batchCreate (CloudStoreList) returns (CloudStoreList) {}
	Get(ctx context.Context, in *CloudStore, opts ...grpc.CallOption) (*CloudStore, error)
	Update(ctx context.Context, in *CloudStore, opts ...grpc.CallOption) (*CloudStore, error)
	BatchGet(ctx context.Context, in *CloudStoreList, opts ...grpc.CallOption) (*CloudStoreList, error)
	GetDownloadAddress(ctx context.Context, in *CloudStore, opts ...grpc.CallOption) (*CloudStore, error)
	UploadToken(ctx context.Context, in *CloudStore, opts ...grpc.CallOption) (*CloudStore, error)
}

type cloudStoreServiceClient struct {
	cc *grpc.ClientConn
}

func NewCloudStoreServiceClient(cc *grpc.ClientConn) CloudStoreServiceClient {
	return &cloudStoreServiceClient{cc}
}

func (c *cloudStoreServiceClient) Create(ctx context.Context, in *CloudStore, opts ...grpc.CallOption) (*CloudStore, error) {
	out := new(CloudStore)
	err := c.cc.Invoke(ctx, "/services.CloudStoreService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudStoreServiceClient) Get(ctx context.Context, in *CloudStore, opts ...grpc.CallOption) (*CloudStore, error) {
	out := new(CloudStore)
	err := c.cc.Invoke(ctx, "/services.CloudStoreService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudStoreServiceClient) Update(ctx context.Context, in *CloudStore, opts ...grpc.CallOption) (*CloudStore, error) {
	out := new(CloudStore)
	err := c.cc.Invoke(ctx, "/services.CloudStoreService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudStoreServiceClient) BatchGet(ctx context.Context, in *CloudStoreList, opts ...grpc.CallOption) (*CloudStoreList, error) {
	out := new(CloudStoreList)
	err := c.cc.Invoke(ctx, "/services.CloudStoreService/BatchGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudStoreServiceClient) GetDownloadAddress(ctx context.Context, in *CloudStore, opts ...grpc.CallOption) (*CloudStore, error) {
	out := new(CloudStore)
	err := c.cc.Invoke(ctx, "/services.CloudStoreService/GetDownloadAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudStoreServiceClient) UploadToken(ctx context.Context, in *CloudStore, opts ...grpc.CallOption) (*CloudStore, error) {
	out := new(CloudStore)
	err := c.cc.Invoke(ctx, "/services.CloudStoreService/UploadToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudStoreServiceServer is the server API for CloudStoreService service.
type CloudStoreServiceServer interface {
	Create(context.Context, *CloudStore) (*CloudStore, error)
	// rpc tryCreate (CloudStore) returns (CloudStore) {}
	// rpc batchCreate (CloudStoreList) returns (CloudStoreList) {}
	Get(context.Context, *CloudStore) (*CloudStore, error)
	Update(context.Context, *CloudStore) (*CloudStore, error)
	BatchGet(context.Context, *CloudStoreList) (*CloudStoreList, error)
	GetDownloadAddress(context.Context, *CloudStore) (*CloudStore, error)
	UploadToken(context.Context, *CloudStore) (*CloudStore, error)
}

// UnimplementedCloudStoreServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCloudStoreServiceServer struct {
}

func (*UnimplementedCloudStoreServiceServer) Create(ctx context.Context, req *CloudStore) (*CloudStore, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedCloudStoreServiceServer) Get(ctx context.Context, req *CloudStore) (*CloudStore, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedCloudStoreServiceServer) Update(ctx context.Context, req *CloudStore) (*CloudStore, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedCloudStoreServiceServer) BatchGet(ctx context.Context, req *CloudStoreList) (*CloudStoreList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGet not implemented")
}
func (*UnimplementedCloudStoreServiceServer) GetDownloadAddress(ctx context.Context, req *CloudStore) (*CloudStore, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDownloadAddress not implemented")
}
func (*UnimplementedCloudStoreServiceServer) UploadToken(ctx context.Context, req *CloudStore) (*CloudStore, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadToken not implemented")
}

func RegisterCloudStoreServiceServer(s *grpc.Server, srv CloudStoreServiceServer) {
	s.RegisterService(&_CloudStoreService_serviceDesc, srv)
}

func _CloudStoreService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloudStore)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudStoreServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.CloudStoreService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudStoreServiceServer).Create(ctx, req.(*CloudStore))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudStoreService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloudStore)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudStoreServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.CloudStoreService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudStoreServiceServer).Get(ctx, req.(*CloudStore))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudStoreService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloudStore)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudStoreServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.CloudStoreService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudStoreServiceServer).Update(ctx, req.(*CloudStore))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudStoreService_BatchGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloudStoreList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudStoreServiceServer).BatchGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.CloudStoreService/BatchGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudStoreServiceServer).BatchGet(ctx, req.(*CloudStoreList))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudStoreService_GetDownloadAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloudStore)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudStoreServiceServer).GetDownloadAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.CloudStoreService/GetDownloadAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudStoreServiceServer).GetDownloadAddress(ctx, req.(*CloudStore))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudStoreService_UploadToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloudStore)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudStoreServiceServer).UploadToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.CloudStoreService/UploadToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudStoreServiceServer).UploadToken(ctx, req.(*CloudStore))
	}
	return interceptor(ctx, in, info, handler)
}

var _CloudStoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.CloudStoreService",
	HandlerType: (*CloudStoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CloudStoreService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _CloudStoreService_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CloudStoreService_Update_Handler,
		},
		{
			MethodName: "BatchGet",
			Handler:    _CloudStoreService_BatchGet_Handler,
		},
		{
			MethodName: "GetDownloadAddress",
			Handler:    _CloudStoreService_GetDownloadAddress_Handler,
		},
		{
			MethodName: "UploadToken",
			Handler:    _CloudStoreService_UploadToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "store/cloudstore.proto",
}
