// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/userfile.proto

package userfile

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "github.com/zzzhr1990/common-grpc/go/common"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GrpcUserFile struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	StoreIdentity        string   `protobuf:"bytes,2,opt,name=storeIdentity,proto3" json:"storeIdentity,omitempty"`
	UserIdentity         int64    `protobuf:"varint,3,opt,name=userIdentity,proto3" json:"userIdentity,omitempty"`
	Path                 string   `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Ext                  string   `protobuf:"bytes,6,opt,name=ext,proto3" json:"ext,omitempty"`
	Size                 uint64   `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	Parent               string   `protobuf:"bytes,8,opt,name=parent,proto3" json:"parent,omitempty"`
	Type                 int32    `protobuf:"varint,9,opt,name=type,proto3" json:"type,omitempty"`
	IsDirectory          bool     `protobuf:"varint,10,opt,name=isDirectory,proto3" json:"isDirectory,omitempty"`
	Atime                int64    `protobuf:"varint,11,opt,name=atime,proto3" json:"atime,omitempty"`
	Ctime                int64    `protobuf:"varint,12,opt,name=ctime,proto3" json:"ctime,omitempty"`
	Mtime                int64    `protobuf:"varint,13,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Version              uint32   `protobuf:"varint,14,opt,name=version,proto3" json:"version,omitempty"`
	Locking              bool     `protobuf:"varint,15,opt,name=locking,proto3" json:"locking,omitempty"`
	Op                   uint32   `protobuf:"varint,16,opt,name=op,proto3" json:"op,omitempty"`
	IgnoreCase           bool     `protobuf:"varint,17,opt,name=ignoreCase,proto3" json:"ignoreCase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrpcUserFile) Reset()         { *m = GrpcUserFile{} }
func (m *GrpcUserFile) String() string { return proto.CompactTextString(m) }
func (*GrpcUserFile) ProtoMessage()    {}
func (*GrpcUserFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6806edd9a7324ee, []int{0}
}

func (m *GrpcUserFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcUserFile.Unmarshal(m, b)
}
func (m *GrpcUserFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcUserFile.Marshal(b, m, deterministic)
}
func (m *GrpcUserFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcUserFile.Merge(m, src)
}
func (m *GrpcUserFile) XXX_Size() int {
	return xxx_messageInfo_GrpcUserFile.Size(m)
}
func (m *GrpcUserFile) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcUserFile.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcUserFile proto.InternalMessageInfo

func (m *GrpcUserFile) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *GrpcUserFile) GetStoreIdentity() string {
	if m != nil {
		return m.StoreIdentity
	}
	return ""
}

func (m *GrpcUserFile) GetUserIdentity() int64 {
	if m != nil {
		return m.UserIdentity
	}
	return 0
}

func (m *GrpcUserFile) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *GrpcUserFile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GrpcUserFile) GetExt() string {
	if m != nil {
		return m.Ext
	}
	return ""
}

func (m *GrpcUserFile) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GrpcUserFile) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *GrpcUserFile) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *GrpcUserFile) GetIsDirectory() bool {
	if m != nil {
		return m.IsDirectory
	}
	return false
}

func (m *GrpcUserFile) GetAtime() int64 {
	if m != nil {
		return m.Atime
	}
	return 0
}

func (m *GrpcUserFile) GetCtime() int64 {
	if m != nil {
		return m.Ctime
	}
	return 0
}

func (m *GrpcUserFile) GetMtime() int64 {
	if m != nil {
		return m.Mtime
	}
	return 0
}

func (m *GrpcUserFile) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GrpcUserFile) GetLocking() bool {
	if m != nil {
		return m.Locking
	}
	return false
}

func (m *GrpcUserFile) GetOp() uint32 {
	if m != nil {
		return m.Op
	}
	return 0
}

func (m *GrpcUserFile) GetIgnoreCase() bool {
	if m != nil {
		return m.IgnoreCase
	}
	return false
}

type UserFileOperation struct {
	Source               []*GrpcUserFile `protobuf:"bytes,1,rep,name=source,proto3" json:"source,omitempty"`
	Destnation           *GrpcUserFile   `protobuf:"bytes,2,opt,name=destnation,proto3" json:"destnation,omitempty"`
	OperationCode        int32           `protobuf:"varint,3,opt,name=operationCode,proto3" json:"operationCode,omitempty"`
	UserIdentity         int64           `protobuf:"varint,4,opt,name=userIdentity,proto3" json:"userIdentity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserFileOperation) Reset()         { *m = UserFileOperation{} }
func (m *UserFileOperation) String() string { return proto.CompactTextString(m) }
func (*UserFileOperation) ProtoMessage()    {}
func (*UserFileOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6806edd9a7324ee, []int{1}
}

func (m *UserFileOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserFileOperation.Unmarshal(m, b)
}
func (m *UserFileOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserFileOperation.Marshal(b, m, deterministic)
}
func (m *UserFileOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserFileOperation.Merge(m, src)
}
func (m *UserFileOperation) XXX_Size() int {
	return xxx_messageInfo_UserFileOperation.Size(m)
}
func (m *UserFileOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_UserFileOperation.DiscardUnknown(m)
}

var xxx_messageInfo_UserFileOperation proto.InternalMessageInfo

func (m *UserFileOperation) GetSource() []*GrpcUserFile {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *UserFileOperation) GetDestnation() *GrpcUserFile {
	if m != nil {
		return m.Destnation
	}
	return nil
}

func (m *UserFileOperation) GetOperationCode() int32 {
	if m != nil {
		return m.OperationCode
	}
	return 0
}

func (m *UserFileOperation) GetUserIdentity() int64 {
	if m != nil {
		return m.UserIdentity
	}
	return 0
}

type PagedUserFile struct {
	Parent               *GrpcUserFile   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	List                 []*GrpcUserFile `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	TotalCount           int64           `protobuf:"varint,3,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	TotalPage            int32           `protobuf:"varint,4,opt,name=totalPage,proto3" json:"totalPage,omitempty"`
	Page                 int32           `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32           `protobuf:"varint,6,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PagedUserFile) Reset()         { *m = PagedUserFile{} }
func (m *PagedUserFile) String() string { return proto.CompactTextString(m) }
func (*PagedUserFile) ProtoMessage()    {}
func (*PagedUserFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6806edd9a7324ee, []int{2}
}

func (m *PagedUserFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PagedUserFile.Unmarshal(m, b)
}
func (m *PagedUserFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PagedUserFile.Marshal(b, m, deterministic)
}
func (m *PagedUserFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PagedUserFile.Merge(m, src)
}
func (m *PagedUserFile) XXX_Size() int {
	return xxx_messageInfo_PagedUserFile.Size(m)
}
func (m *PagedUserFile) XXX_DiscardUnknown() {
	xxx_messageInfo_PagedUserFile.DiscardUnknown(m)
}

var xxx_messageInfo_PagedUserFile proto.InternalMessageInfo

func (m *PagedUserFile) GetParent() *GrpcUserFile {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *PagedUserFile) GetList() []*GrpcUserFile {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *PagedUserFile) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *PagedUserFile) GetTotalPage() int32 {
	if m != nil {
		return m.TotalPage
	}
	return 0
}

func (m *PagedUserFile) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PagedUserFile) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type UserFileList struct {
	Parent               *GrpcUserFile   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	List                 []*GrpcUserFile `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserFileList) Reset()         { *m = UserFileList{} }
func (m *UserFileList) String() string { return proto.CompactTextString(m) }
func (*UserFileList) ProtoMessage()    {}
func (*UserFileList) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6806edd9a7324ee, []int{3}
}

func (m *UserFileList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserFileList.Unmarshal(m, b)
}
func (m *UserFileList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserFileList.Marshal(b, m, deterministic)
}
func (m *UserFileList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserFileList.Merge(m, src)
}
func (m *UserFileList) XXX_Size() int {
	return xxx_messageInfo_UserFileList.Size(m)
}
func (m *UserFileList) XXX_DiscardUnknown() {
	xxx_messageInfo_UserFileList.DiscardUnknown(m)
}

var xxx_messageInfo_UserFileList proto.InternalMessageInfo

func (m *UserFileList) GetParent() *GrpcUserFile {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *UserFileList) GetList() []*GrpcUserFile {
	if m != nil {
		return m.List
	}
	return nil
}

type PagedUserFileRequest struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	UserIdentity         int64    `protobuf:"varint,3,opt,name=userIdentity,proto3" json:"userIdentity,omitempty"`
	IgnoreCase           bool     `protobuf:"varint,4,opt,name=ignoreCase,proto3" json:"ignoreCase,omitempty"`
	OrderBy              int32    `protobuf:"varint,5,opt,name=orderBy,proto3" json:"orderBy,omitempty"`
	Page                 int32    `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,7,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PagedUserFileRequest) Reset()         { *m = PagedUserFileRequest{} }
func (m *PagedUserFileRequest) String() string { return proto.CompactTextString(m) }
func (*PagedUserFileRequest) ProtoMessage()    {}
func (*PagedUserFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6806edd9a7324ee, []int{4}
}

func (m *PagedUserFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PagedUserFileRequest.Unmarshal(m, b)
}
func (m *PagedUserFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PagedUserFileRequest.Marshal(b, m, deterministic)
}
func (m *PagedUserFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PagedUserFileRequest.Merge(m, src)
}
func (m *PagedUserFileRequest) XXX_Size() int {
	return xxx_messageInfo_PagedUserFileRequest.Size(m)
}
func (m *PagedUserFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PagedUserFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PagedUserFileRequest proto.InternalMessageInfo

func (m *PagedUserFileRequest) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *PagedUserFileRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *PagedUserFileRequest) GetUserIdentity() int64 {
	if m != nil {
		return m.UserIdentity
	}
	return 0
}

func (m *PagedUserFileRequest) GetIgnoreCase() bool {
	if m != nil {
		return m.IgnoreCase
	}
	return false
}

func (m *PagedUserFileRequest) GetOrderBy() int32 {
	if m != nil {
		return m.OrderBy
	}
	return 0
}

func (m *PagedUserFileRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PagedUserFileRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ListUserFileRequest struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	UserIdentity         int64    `protobuf:"varint,3,opt,name=userIdentity,proto3" json:"userIdentity,omitempty"`
	IgnoreCase           bool     `protobuf:"varint,4,opt,name=ignoreCase,proto3" json:"ignoreCase,omitempty"`
	OrderBy              int32    `protobuf:"varint,5,opt,name=orderBy,proto3" json:"orderBy,omitempty"`
	Start                int32    `protobuf:"varint,6,opt,name=start,proto3" json:"start,omitempty"`
	ListSize             int32    `protobuf:"varint,7,opt,name=listSize,proto3" json:"listSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserFileRequest) Reset()         { *m = ListUserFileRequest{} }
func (m *ListUserFileRequest) String() string { return proto.CompactTextString(m) }
func (*ListUserFileRequest) ProtoMessage()    {}
func (*ListUserFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6806edd9a7324ee, []int{5}
}

func (m *ListUserFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserFileRequest.Unmarshal(m, b)
}
func (m *ListUserFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserFileRequest.Marshal(b, m, deterministic)
}
func (m *ListUserFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserFileRequest.Merge(m, src)
}
func (m *ListUserFileRequest) XXX_Size() int {
	return xxx_messageInfo_ListUserFileRequest.Size(m)
}
func (m *ListUserFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserFileRequest proto.InternalMessageInfo

func (m *ListUserFileRequest) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *ListUserFileRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ListUserFileRequest) GetUserIdentity() int64 {
	if m != nil {
		return m.UserIdentity
	}
	return 0
}

func (m *ListUserFileRequest) GetIgnoreCase() bool {
	if m != nil {
		return m.IgnoreCase
	}
	return false
}

func (m *ListUserFileRequest) GetOrderBy() int32 {
	if m != nil {
		return m.OrderBy
	}
	return 0
}

func (m *ListUserFileRequest) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *ListUserFileRequest) GetListSize() int32 {
	if m != nil {
		return m.ListSize
	}
	return 0
}

func init() {
	proto.RegisterType((*GrpcUserFile)(nil), "services.GrpcUserFile")
	proto.RegisterType((*UserFileOperation)(nil), "services.UserFileOperation")
	proto.RegisterType((*PagedUserFile)(nil), "services.PagedUserFile")
	proto.RegisterType((*UserFileList)(nil), "services.UserFileList")
	proto.RegisterType((*PagedUserFileRequest)(nil), "services.PagedUserFileRequest")
	proto.RegisterType((*ListUserFileRequest)(nil), "services.ListUserFileRequest")
}

func init() { proto.RegisterFile("user/userfile.proto", fileDescriptor_d6806edd9a7324ee) }

var fileDescriptor_d6806edd9a7324ee = []byte{
	// 723 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0xcd, 0x6e, 0xd3, 0x4a,
	0x14, 0x8e, 0xf3, 0xd7, 0xf4, 0x24, 0xe9, 0xcf, 0xa4, 0xb7, 0x77, 0x94, 0x7b, 0x6f, 0x65, 0x59,
	0x77, 0x61, 0x21, 0x91, 0x40, 0x2b, 0x40, 0x5d, 0x21, 0xa5, 0xb4, 0xa5, 0x12, 0x52, 0x2b, 0x57,
	0x6c, 0xd8, 0x20, 0xd7, 0x39, 0xb8, 0x03, 0xb1, 0xc7, 0xcc, 0x4c, 0x2a, 0x92, 0x07, 0xe3, 0x0d,
	0x10, 0x2f, 0x00, 0x0b, 0xde, 0x06, 0xcd, 0x38, 0x76, 0x9c, 0xb6, 0xa9, 0x10, 0x08, 0x89, 0x4d,
	0x32, 0xe7, 0xf3, 0x37, 0x67, 0xce, 0xcf, 0x77, 0x66, 0xa0, 0x33, 0x96, 0x28, 0xfa, 0xfa, 0xe7,
	0x0d, 0x1b, 0x61, 0x2f, 0x11, 0x5c, 0x71, 0xd2, 0x90, 0x28, 0xae, 0x58, 0x80, 0xb2, 0xdb, 0x0d,
	0x78, 0x14, 0xf1, 0xb8, 0x9f, 0xfe, 0xbd, 0xc6, 0x58, 0x31, 0x35, 0x49, 0x59, 0xce, 0xc7, 0x0a,
	0xb4, 0x8e, 0x45, 0x12, 0xbc, 0x94, 0x28, 0x8e, 0xd8, 0x08, 0x49, 0x17, 0x1a, 0x6c, 0x98, 0x52,
	0xa8, 0x65, 0x5b, 0xee, 0xaa, 0x97, 0xdb, 0xe4, 0x7f, 0x68, 0x4b, 0xc5, 0x05, 0x9e, 0x64, 0x84,
	0xb2, 0x21, 0x2c, 0x82, 0xc4, 0x81, 0x96, 0x0e, 0x25, 0x27, 0x55, 0x6c, 0xcb, 0xad, 0x78, 0x0b,
	0x18, 0x21, 0x50, 0x4d, 0x7c, 0x75, 0x49, 0xab, 0xc6, 0x81, 0x59, 0x6b, 0x2c, 0xf6, 0x23, 0xa4,
	0xb5, 0x14, 0xd3, 0x6b, 0xb2, 0x01, 0x15, 0xfc, 0xa0, 0x68, 0xdd, 0x40, 0x7a, 0xa9, 0x59, 0x92,
	0x4d, 0x91, 0xae, 0xd8, 0x96, 0x5b, 0xf5, 0xcc, 0x9a, 0x6c, 0x43, 0x3d, 0xf1, 0x05, 0xc6, 0x8a,
	0x36, 0x0c, 0x71, 0x66, 0x69, 0xae, 0x9a, 0x24, 0x48, 0x57, 0x6d, 0xcb, 0xad, 0x79, 0x66, 0x4d,
	0x6c, 0x68, 0x32, 0xf9, 0x8c, 0x09, 0x0c, 0x14, 0x17, 0x13, 0x0a, 0xb6, 0xe5, 0x36, 0xbc, 0x22,
	0x44, 0xb6, 0xa0, 0xe6, 0x2b, 0x16, 0x21, 0x6d, 0x9a, 0xc0, 0x53, 0x43, 0xa3, 0x81, 0x41, 0x5b,
	0x29, 0x1a, 0x64, 0x68, 0x64, 0xd0, 0x76, 0x8a, 0x1a, 0x83, 0x50, 0x58, 0xb9, 0x42, 0x21, 0x19,
	0x8f, 0xe9, 0x9a, 0x6d, 0xb9, 0x6d, 0x2f, 0x33, 0xf5, 0x97, 0x11, 0x0f, 0xde, 0xb1, 0x38, 0xa4,
	0xeb, 0xe6, 0xe4, 0xcc, 0x24, 0x6b, 0x50, 0xe6, 0x09, 0xdd, 0x30, 0xf4, 0x32, 0x4f, 0xc8, 0x0e,
	0x00, 0x0b, 0x63, 0x2e, 0xf0, 0xc0, 0x97, 0x48, 0x37, 0x0d, 0xb9, 0x80, 0x38, 0x9f, 0x2c, 0xd8,
	0xcc, 0x9a, 0x76, 0x9a, 0xa0, 0xf0, 0x95, 0xf6, 0xdf, 0x83, 0xba, 0xe4, 0x63, 0x11, 0x20, 0xb5,
	0xec, 0x8a, 0xdb, 0xdc, 0xdd, 0xee, 0x65, 0x2a, 0xe8, 0x15, 0xbb, 0xec, 0xcd, 0x58, 0xe4, 0x31,
	0xc0, 0x10, 0xa5, 0x8a, 0xcd, 0x6e, 0xd3, 0xce, 0xe5, 0x7b, 0x0a, 0x4c, 0xad, 0x04, 0x9e, 0x1d,
	0x7a, 0xc0, 0x87, 0x68, 0x9a, 0x5c, 0xf3, 0x16, 0xc1, 0x1b, 0x4a, 0xa8, 0xde, 0x54, 0x82, 0xf3,
	0xcd, 0x82, 0xf6, 0x99, 0x1f, 0xe2, 0x30, 0x57, 0x60, 0x2f, 0xef, 0xa6, 0x75, 0x67, 0x3c, 0x59,
	0x97, 0xef, 0x41, 0x75, 0xc4, 0xa4, 0xa2, 0xe5, 0x3b, 0x33, 0x36, 0x1c, 0x5d, 0x55, 0xc5, 0x95,
	0x3f, 0x3a, 0xe0, 0xe3, 0x58, 0xcd, 0x94, 0x59, 0x40, 0xc8, 0xbf, 0xb0, 0x6a, 0x2c, 0x1d, 0x91,
	0x09, 0xb7, 0xe6, 0xcd, 0x81, 0x54, 0xb5, 0x61, 0xaa, 0xd0, 0x9a, 0x67, 0xd6, 0x7a, 0x5e, 0xf4,
	0xff, 0xb9, 0xd6, 0x64, 0xdd, 0xe0, 0xb9, 0xed, 0xbc, 0x85, 0x56, 0x76, 0xfe, 0x0b, 0x7d, 0xfa,
	0x6f, 0xcc, 0xcc, 0xf9, 0x62, 0xc1, 0xd6, 0x42, 0x1d, 0x3d, 0x7c, 0x3f, 0x46, 0xa9, 0xee, 0x1c,
	0xe8, 0x6c, 0x0c, 0xcb, 0x85, 0x31, 0xfc, 0x91, 0xf1, 0x5d, 0x14, 0x67, 0xf5, 0xba, 0x38, 0xb5,
	0xcc, 0xb9, 0x18, 0xa2, 0x18, 0x4c, 0x66, 0xb5, 0xca, 0xcc, 0xbc, 0x84, 0xf5, 0x25, 0x25, 0x5c,
	0xb9, 0x56, 0xc2, 0xaf, 0x16, 0x74, 0x74, 0xed, 0xfe, 0xec, 0xac, 0xb6, 0xa0, 0x26, 0x95, 0x2f,
	0xd4, 0x2c, 0xad, 0xd4, 0xd0, 0x31, 0xea, 0xd6, 0x14, 0xf3, 0xca, 0xec, 0xdd, 0xcf, 0x15, 0xe8,
	0x14, 0xbb, 0x78, 0x9e, 0xb6, 0x96, 0x0c, 0x60, 0x2d, 0x10, 0xe8, 0x2b, 0xcc, 0xc7, 0x61, 0x49,
	0xdb, 0xbb, 0x4b, 0x70, 0xa7, 0x44, 0x9e, 0x42, 0x33, 0x44, 0xf5, 0x0b, 0x0e, 0x8e, 0x80, 0x14,
	0x1c, 0x9c, 0x8a, 0xc3, 0x28, 0x51, 0x93, 0x9f, 0xf0, 0x73, 0x06, 0x1d, 0x9d, 0x70, 0x7e, 0xb5,
	0x0e, 0x26, 0x66, 0x8c, 0x76, 0xe6, 0x1b, 0x6e, 0x53, 0x6c, 0xf7, 0xef, 0x25, 0xdf, 0x9d, 0x12,
	0x79, 0x0e, 0xed, 0x05, 0x8f, 0xe4, 0xbf, 0x39, 0xf7, 0x16, 0x99, 0x14, 0x63, 0x2b, 0x4e, 0xa2,
	0x53, 0x22, 0xc7, 0xb0, 0x9e, 0x5e, 0x56, 0xf3, 0x4a, 0xff, 0x73, 0x93, 0x9c, 0xdf, 0xac, 0xdd,
	0xbf, 0xe6, 0x1f, 0x4f, 0x62, 0xb5, 0xb7, 0x7b, 0x98, 0x5e, 0x5f, 0xa5, 0xc1, 0x93, 0x57, 0x8f,
	0x42, 0xa6, 0x2e, 0xc7, 0x17, 0xbd, 0x80, 0x47, 0xfd, 0xe9, 0x74, 0x7a, 0x29, 0x1e, 0xee, 0xef,
	0x3f, 0x98, 0xbd, 0xb6, 0xf7, 0x43, 0x91, 0x04, 0xfd, 0x90, 0xf7, 0xb3, 0xdd, 0xf9, 0x33, 0x7d,
	0x51, 0x37, 0x2f, 0xf0, 0xde, 0xf7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x46, 0xe9, 0xd8, 0x6b, 0xbe,
	0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GrpcUserFileServiceClient is the client API for GrpcUserFileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpcUserFileServiceClient interface {
	// rpc createUser (GrpcUser) returns (BoolEntity) {}
	// rpc getUser (Uint64Entity) returns (GrpcUser) {}
	CreateUserFile(ctx context.Context, in *GrpcUserFile, opts ...grpc.CallOption) (*GrpcUserFile, error)
	GetUserFile(ctx context.Context, in *GrpcUserFile, opts ...grpc.CallOption) (*GrpcUserFile, error)
	GetUserFileOrEmpty(ctx context.Context, in *GrpcUserFile, opts ...grpc.CallOption) (*GrpcUserFile, error)
	ListDirectoryByPage(ctx context.Context, in *PagedUserFileRequest, opts ...grpc.CallOption) (*PagedUserFile, error)
	ListDirectory(ctx context.Context, in *ListUserFileRequest, opts ...grpc.CallOption) (*UserFileList, error)
	OperateUserFile(ctx context.Context, in *UserFileOperation, opts ...grpc.CallOption) (*common.Int32Entity, error)
}

type grpcUserFileServiceClient struct {
	cc *grpc.ClientConn
}

func NewGrpcUserFileServiceClient(cc *grpc.ClientConn) GrpcUserFileServiceClient {
	return &grpcUserFileServiceClient{cc}
}

func (c *grpcUserFileServiceClient) CreateUserFile(ctx context.Context, in *GrpcUserFile, opts ...grpc.CallOption) (*GrpcUserFile, error) {
	out := new(GrpcUserFile)
	err := c.cc.Invoke(ctx, "/services.GrpcUserFileService/createUserFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcUserFileServiceClient) GetUserFile(ctx context.Context, in *GrpcUserFile, opts ...grpc.CallOption) (*GrpcUserFile, error) {
	out := new(GrpcUserFile)
	err := c.cc.Invoke(ctx, "/services.GrpcUserFileService/getUserFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcUserFileServiceClient) GetUserFileOrEmpty(ctx context.Context, in *GrpcUserFile, opts ...grpc.CallOption) (*GrpcUserFile, error) {
	out := new(GrpcUserFile)
	err := c.cc.Invoke(ctx, "/services.GrpcUserFileService/getUserFileOrEmpty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcUserFileServiceClient) ListDirectoryByPage(ctx context.Context, in *PagedUserFileRequest, opts ...grpc.CallOption) (*PagedUserFile, error) {
	out := new(PagedUserFile)
	err := c.cc.Invoke(ctx, "/services.GrpcUserFileService/listDirectoryByPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcUserFileServiceClient) ListDirectory(ctx context.Context, in *ListUserFileRequest, opts ...grpc.CallOption) (*UserFileList, error) {
	out := new(UserFileList)
	err := c.cc.Invoke(ctx, "/services.GrpcUserFileService/listDirectory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcUserFileServiceClient) OperateUserFile(ctx context.Context, in *UserFileOperation, opts ...grpc.CallOption) (*common.Int32Entity, error) {
	out := new(common.Int32Entity)
	err := c.cc.Invoke(ctx, "/services.GrpcUserFileService/operateUserFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcUserFileServiceServer is the server API for GrpcUserFileService service.
type GrpcUserFileServiceServer interface {
	// rpc createUser (GrpcUser) returns (BoolEntity) {}
	// rpc getUser (Uint64Entity) returns (GrpcUser) {}
	CreateUserFile(context.Context, *GrpcUserFile) (*GrpcUserFile, error)
	GetUserFile(context.Context, *GrpcUserFile) (*GrpcUserFile, error)
	GetUserFileOrEmpty(context.Context, *GrpcUserFile) (*GrpcUserFile, error)
	ListDirectoryByPage(context.Context, *PagedUserFileRequest) (*PagedUserFile, error)
	ListDirectory(context.Context, *ListUserFileRequest) (*UserFileList, error)
	OperateUserFile(context.Context, *UserFileOperation) (*common.Int32Entity, error)
}

func RegisterGrpcUserFileServiceServer(s *grpc.Server, srv GrpcUserFileServiceServer) {
	s.RegisterService(&_GrpcUserFileService_serviceDesc, srv)
}

func _GrpcUserFileService_CreateUserFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcUserFile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcUserFileServiceServer).CreateUserFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.GrpcUserFileService/CreateUserFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcUserFileServiceServer).CreateUserFile(ctx, req.(*GrpcUserFile))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcUserFileService_GetUserFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcUserFile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcUserFileServiceServer).GetUserFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.GrpcUserFileService/GetUserFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcUserFileServiceServer).GetUserFile(ctx, req.(*GrpcUserFile))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcUserFileService_GetUserFileOrEmpty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcUserFile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcUserFileServiceServer).GetUserFileOrEmpty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.GrpcUserFileService/GetUserFileOrEmpty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcUserFileServiceServer).GetUserFileOrEmpty(ctx, req.(*GrpcUserFile))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcUserFileService_ListDirectoryByPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PagedUserFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcUserFileServiceServer).ListDirectoryByPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.GrpcUserFileService/ListDirectoryByPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcUserFileServiceServer).ListDirectoryByPage(ctx, req.(*PagedUserFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcUserFileService_ListDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcUserFileServiceServer).ListDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.GrpcUserFileService/ListDirectory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcUserFileServiceServer).ListDirectory(ctx, req.(*ListUserFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcUserFileService_OperateUserFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserFileOperation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcUserFileServiceServer).OperateUserFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.GrpcUserFileService/OperateUserFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcUserFileServiceServer).OperateUserFile(ctx, req.(*UserFileOperation))
	}
	return interceptor(ctx, in, info, handler)
}

var _GrpcUserFileService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.GrpcUserFileService",
	HandlerType: (*GrpcUserFileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createUserFile",
			Handler:    _GrpcUserFileService_CreateUserFile_Handler,
		},
		{
			MethodName: "getUserFile",
			Handler:    _GrpcUserFileService_GetUserFile_Handler,
		},
		{
			MethodName: "getUserFileOrEmpty",
			Handler:    _GrpcUserFileService_GetUserFileOrEmpty_Handler,
		},
		{
			MethodName: "listDirectoryByPage",
			Handler:    _GrpcUserFileService_ListDirectoryByPage_Handler,
		},
		{
			MethodName: "listDirectory",
			Handler:    _GrpcUserFileService_ListDirectory_Handler,
		},
		{
			MethodName: "operateUserFile",
			Handler:    _GrpcUserFileService_OperateUserFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/userfile.proto",
}
