// Code generated by protoc-gen-go. DO NOT EDIT.
// source: share/share.proto

package fileshare

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// FC
type FileShare struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Mime                 string   `protobuf:"bytes,3,opt,name=mime,proto3" json:"mime,omitempty"`
	User                 int64    `protobuf:"varint,4,opt,name=user,proto3" json:"user,omitempty"`
	Ctime                int64    `protobuf:"varint,5,opt,name=ctime,proto3" json:"ctime,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Flag                 int32    `protobuf:"varint,7,opt,name=flag,proto3" json:"flag,omitempty"`
	PasswordEnabled      bool     `protobuf:"varint,8,opt,name=passwordEnabled,proto3" json:"passwordEnabled,omitempty"`
	Password             string   `protobuf:"bytes,9,opt,name=password,proto3" json:"password,omitempty"`
	ExpireEnabled        bool     `protobuf:"varint,10,opt,name=expireEnabled,proto3" json:"expireEnabled,omitempty"`
	Expire               int64    `protobuf:"varint,11,opt,name=expire,proto3" json:"expire,omitempty"`
	CopyCount            int64    `protobuf:"varint,12,opt,name=copyCount,proto3" json:"copyCount,omitempty"`
	CopyCountLeft        int64    `protobuf:"varint,13,opt,name=copyCountLeft,proto3" json:"copyCountLeft,omitempty"`
	CopyCountEnabled     bool     `protobuf:"varint,14,opt,name=copyCountEnabled,proto3" json:"copyCountEnabled,omitempty"`
	Expired              bool     `protobuf:"varint,15,opt,name=expired,proto3" json:"expired,omitempty"`
	ExpicopyExceed       bool     `protobuf:"varint,16,opt,name=expicopyExceed,proto3" json:"expicopyExceed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileShare) Reset()         { *m = FileShare{} }
func (m *FileShare) String() string { return proto.CompactTextString(m) }
func (*FileShare) ProtoMessage()    {}
func (*FileShare) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa89f5b0d847a47e, []int{0}
}

func (m *FileShare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileShare.Unmarshal(m, b)
}
func (m *FileShare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileShare.Marshal(b, m, deterministic)
}
func (m *FileShare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileShare.Merge(m, src)
}
func (m *FileShare) XXX_Size() int {
	return xxx_messageInfo_FileShare.Size(m)
}
func (m *FileShare) XXX_DiscardUnknown() {
	xxx_messageInfo_FileShare.DiscardUnknown(m)
}

var xxx_messageInfo_FileShare proto.InternalMessageInfo

func (m *FileShare) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *FileShare) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileShare) GetMime() string {
	if m != nil {
		return m.Mime
	}
	return ""
}

func (m *FileShare) GetUser() int64 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *FileShare) GetCtime() int64 {
	if m != nil {
		return m.Ctime
	}
	return 0
}

func (m *FileShare) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileShare) GetFlag() int32 {
	if m != nil {
		return m.Flag
	}
	return 0
}

func (m *FileShare) GetPasswordEnabled() bool {
	if m != nil {
		return m.PasswordEnabled
	}
	return false
}

func (m *FileShare) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *FileShare) GetExpireEnabled() bool {
	if m != nil {
		return m.ExpireEnabled
	}
	return false
}

func (m *FileShare) GetExpire() int64 {
	if m != nil {
		return m.Expire
	}
	return 0
}

func (m *FileShare) GetCopyCount() int64 {
	if m != nil {
		return m.CopyCount
	}
	return 0
}

func (m *FileShare) GetCopyCountLeft() int64 {
	if m != nil {
		return m.CopyCountLeft
	}
	return 0
}

func (m *FileShare) GetCopyCountEnabled() bool {
	if m != nil {
		return m.CopyCountEnabled
	}
	return false
}

func (m *FileShare) GetExpired() bool {
	if m != nil {
		return m.Expired
	}
	return false
}

func (m *FileShare) GetExpicopyExceed() bool {
	if m != nil {
		return m.ExpicopyExceed
	}
	return false
}

func init() {
	proto.RegisterType((*FileShare)(nil), "services.FileShare")
}

func init() { proto.RegisterFile("share/share.proto", fileDescriptor_fa89f5b0d847a47e) }

var fileDescriptor_fa89f5b0d847a47e = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x4f, 0xab, 0xd3, 0x40,
	0x14, 0xc5, 0x8d, 0x6d, 0xd3, 0xe4, 0x6a, 0xff, 0x38, 0x8a, 0x0c, 0xc5, 0x45, 0x28, 0x22, 0x41,
	0x30, 0xf1, 0xdf, 0xc2, 0x82, 0xb8, 0x50, 0xea, 0x4a, 0x10, 0xd2, 0x9d, 0xbb, 0x74, 0x72, 0x9b,
	0x0e, 0x24, 0x99, 0x30, 0x99, 0x6a, 0x9b, 0xa5, 0x5f, 0xf2, 0x7d, 0x9d, 0xc7, 0xcc, 0xbc, 0xe4,
	0xd1, 0xbe, 0xb7, 0x79, 0x9b, 0x70, 0xce, 0x6f, 0xce, 0x9d, 0x1c, 0x98, 0x0b, 0xcf, 0x9a, 0x7d,
	0x2a, 0x31, 0x36, 0xdf, 0xa8, 0x96, 0x42, 0x09, 0xe2, 0x35, 0x28, 0xff, 0x72, 0x86, 0xcd, 0xf2,
	0x6a, 0x00, 0xfe, 0x4f, 0x5e, 0xe0, 0x46, 0x9f, 0x92, 0x05, 0x78, 0x3c, 0xc3, 0x4a, 0x71, 0x75,
	0xa2, 0x4e, 0xe0, 0x84, 0x7e, 0xd2, 0x7b, 0x42, 0x60, 0xd8, 0xf0, 0x16, 0xe9, 0xe3, 0xc0, 0x09,
	0x07, 0x89, 0xd1, 0x9a, 0x95, 0xbc, 0x44, 0x3a, 0x30, 0x59, 0xa3, 0x35, 0x3b, 0x34, 0x28, 0xe9,
	0xd0, 0xe6, 0xb4, 0x26, 0x2f, 0x60, 0xc4, 0x94, 0x0e, 0x8e, 0x0c, 0xb4, 0x46, 0x27, 0xab, 0xb4,
	0x44, 0xea, 0xda, 0x69, 0xad, 0x35, 0xdb, 0x15, 0x69, 0x4e, 0xc7, 0x81, 0x13, 0x8e, 0x12, 0xa3,
	0x49, 0x08, 0xb3, 0x3a, 0x6d, 0x9a, 0x7f, 0x42, 0x66, 0xeb, 0x2a, 0xdd, 0x16, 0x98, 0x51, 0x2f,
	0x70, 0x42, 0x2f, 0xb9, 0xc4, 0xba, 0x7f, 0x87, 0xa8, 0x6f, 0xfb, 0x77, 0x9e, 0xbc, 0x86, 0x09,
	0x1e, 0x6b, 0x2e, 0xb1, 0xbb, 0x03, 0xcc, 0x1d, 0xe7, 0x90, 0xbc, 0x04, 0xd7, 0x02, 0xfa, 0xc4,
	0x54, 0xbd, 0x71, 0xe4, 0x15, 0xf8, 0x4c, 0xd4, 0xa7, 0x1f, 0xe2, 0x50, 0x29, 0xfa, 0xd4, 0x1c,
	0xdd, 0x02, 0x7d, 0x77, 0x6f, 0x7e, 0xe1, 0x4e, 0xd1, 0x89, 0x49, 0x9c, 0x43, 0xf2, 0x16, 0xe6,
	0x3d, 0xe8, 0x4a, 0x4c, 0x4d, 0x89, 0x3b, 0x9c, 0x50, 0x18, 0xdb, 0x3f, 0x67, 0x74, 0x66, 0x22,
	0x9d, 0x25, 0x6f, 0x60, 0xaa, 0xa5, 0x9e, 0x58, 0x1f, 0x19, 0x62, 0x46, 0xe7, 0x26, 0x70, 0x41,
	0x3f, 0xfe, 0x77, 0x60, 0xde, 0xbf, 0xec, 0xc6, 0xbe, 0x37, 0xf9, 0x0c, 0x2e, 0x93, 0x98, 0x2a,
	0x24, 0xcf, 0xa3, 0x6e, 0x07, 0xa2, 0x3e, 0xb5, 0xb8, 0x0f, 0x2e, 0x1f, 0x91, 0x2f, 0x00, 0x39,
	0xaa, 0xdf, 0x72, 0x5d, 0xd6, 0xea, 0xf4, 0x90, 0xc9, 0xef, 0xdf, 0xfe, 0x7c, 0xcd, 0xb9, 0xda,
	0x1f, 0xb6, 0x11, 0x13, 0x65, 0xdc, 0xb6, 0xed, 0x5e, 0x7e, 0x58, 0xad, 0xde, 0xc7, 0x4c, 0x94,
	0xa5, 0xa8, 0xde, 0xe5, 0xb2, 0x66, 0x71, 0x2e, 0xe2, 0x6e, 0xd6, 0x2e, 0x69, 0xbc, 0xe3, 0x05,
	0x1a, 0xb5, 0x75, 0xcd, 0xbe, 0x7e, 0xba, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x3f, 0xeb, 0x00,
	0xc4, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FileShareServiceClient is the client API for FileShareService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FileShareServiceClient interface {
	Create(ctx context.Context, in *FileShare, opts ...grpc.CallOption) (*FileShare, error)
	GetOrEmpty(ctx context.Context, in *FileShare, opts ...grpc.CallOption) (*FileShare, error)
}

type fileShareServiceClient struct {
	cc *grpc.ClientConn
}

func NewFileShareServiceClient(cc *grpc.ClientConn) FileShareServiceClient {
	return &fileShareServiceClient{cc}
}

func (c *fileShareServiceClient) Create(ctx context.Context, in *FileShare, opts ...grpc.CallOption) (*FileShare, error) {
	out := new(FileShare)
	err := c.cc.Invoke(ctx, "/services.FileShareService/create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileShareServiceClient) GetOrEmpty(ctx context.Context, in *FileShare, opts ...grpc.CallOption) (*FileShare, error) {
	out := new(FileShare)
	err := c.cc.Invoke(ctx, "/services.FileShareService/getOrEmpty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileShareServiceServer is the server API for FileShareService service.
type FileShareServiceServer interface {
	Create(context.Context, *FileShare) (*FileShare, error)
	GetOrEmpty(context.Context, *FileShare) (*FileShare, error)
}

// UnimplementedFileShareServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFileShareServiceServer struct {
}

func (*UnimplementedFileShareServiceServer) Create(ctx context.Context, req *FileShare) (*FileShare, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedFileShareServiceServer) GetOrEmpty(ctx context.Context, req *FileShare) (*FileShare, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrEmpty not implemented")
}

func RegisterFileShareServiceServer(s *grpc.Server, srv FileShareServiceServer) {
	s.RegisterService(&_FileShareService_serviceDesc, srv)
}

func _FileShareService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileShare)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileShareServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.FileShareService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileShareServiceServer).Create(ctx, req.(*FileShare))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileShareService_GetOrEmpty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileShare)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileShareServiceServer).GetOrEmpty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.FileShareService/GetOrEmpty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileShareServiceServer).GetOrEmpty(ctx, req.(*FileShare))
	}
	return interceptor(ctx, in, info, handler)
}

var _FileShareService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.FileShareService",
	HandlerType: (*FileShareServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "create",
			Handler:    _FileShareService_Create_Handler,
		},
		{
			MethodName: "getOrEmpty",
			Handler:    _FileShareService_GetOrEmpty_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "share/share.proto",
}
